apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns
  namespace: dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dns-exec
  namespace: dns
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns
  namespace: dns
subjects:
  - kind: ServiceAccount
    name: dns
    namespace: dns
roleRef:
  kind: Role
  name: dns-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dns-cronjob
  namespace: dns
spec:
  concurrencyPolicy: Forbid
  schedule: "0 3 */2 * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: dns
          containers:
            - name: kubectl
              image: ghcr.io/akashisn/kubectl@sha256:73a49b52231a131a7b7781788d59160168c5686eb3f0701d67d2654339ac3534
              imagePullPolicy: IfNotPresent
              args:
                [
                  "rollout",
                  "-n",
                  "dns",
                  "restart",
                  "deployments/dns-server"
                ]
          restartPolicy: Never
