apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkit
  name: buildkit
  namespace: buildkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkit
  template:
    metadata:
      labels:
        app: buildkit
    spec:
      containers:
        - name: buildkit
          image: moby/buildkit:v0.11.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2376
              name: buildkit
          args:
            - --addr
            - unix:///run/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:2376
            - --tlscacert
            - /certs/ca.pem
            - --tlscert
            - /certs/cert.pem
            - --tlskey
            - /certs/key.pem
          # the probe below will only work after Release v0.6.3
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          # the probe below will only work after Release v0.6.3
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 8000m
              memory: 8Gi
            limits:
              cpu: 8000m
              memory: 16Gi
          volumeMounts:
            - name: certs
              readOnly: true
              mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: buildkit-daemon-certs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: buildkit
  name: buildkit
  namespace: buildkit
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  externalIPs:
    - 10.0.1.50
  ports:
    - port: 2376
      name: buildkit
  selector:
    app: buildkit
