apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iscsi-ssd-storage
  claimRef:
    namespace: minecraft
    name: data-minecraft-0
  iscsi:
    targetPortal: 172.16.255.1:3260
    iqn: iqn.2005-10.org.freenas.ctl:minecraft
    lun: 0
    fsType: xfs
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-backup-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-hdd-storage
  claimRef:
    namespace: minecraft
    name: backup-minecraft-0
  nfs:
    server: 172.16.255.1
    path: /mnt/hdd/nfs/minecraft-backup
  mountOptions:
    - nfsvers=4.2
