apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-wordpress-0
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-ssd-storage
  resources:
    requests:
      storage: 30Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-wordpress-mariadb-0
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: iscsi-ssd-storage
  resources:
    requests:
      storage: 30Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ubuntu
  namespace: wordpress
  labels:
    app: ubuntu
spec:
  template:
    metadata:
      name: cleanup
      namespace: wordpress
    spec:
      restartPolicy: Never
      volumes:
        - name: app
          persistentVolumeClaim:
            claimName: app-wordpress-0
        - name: data
          persistentVolumeClaim:
            claimName: data-wordpress-mariadb-0
      containers:
        - name: ubuntu
          image: ubuntu:22.04
          args:
            - rm
            - -rfv
            - /app/{*,.*}
            - /data/{*,.*}
          volumeMounts:
            - mountPath: /app
              name: app
            - mountPath: /data
              name: data
