apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-env
  namespace: palworld
data:
  PUID: "1000"
  PGID: "1000"
  PORT: "8211" # Optional but recommended
  PLAYERS: "16" # Optional but recommended
  MULTITHREADING: "true"
  RCON_ENABLED: "true"
  RCON_PORT: "25575"
  TZ: "Asia/Tokyo"
  COMMUNITY: "false" # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
  SERVER_NAME: "World of Pals"
  SERVER_DESCRIPTION: "Palworld Server powered by Kubernetes"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-settings
  namespace: palworld
data:
  PalWorldSettings.ini: >-
    [/Script/OnlineSubsystemUtils.IpNetDriver]
    NetServerMaxTickRate=60

    [/Script/Pal.PalGameWorldSettings]

    OptionSettings=(
    Difficulty=None,
    DayTimeSpeedRate=1.000000,
    NightTimeSpeedRate=1.000000,
    ExpRate=1.000000,
    PalCaptureRate=1.000000,
    PalSpawnNumRate=1.000000,
    PalDamageRateAttack=1.000000,
    PalDamageRateDefense=1.000000,
    PlayerDamageRateAttack=1.000000,
    PlayerDamageRateDefense=1.000000,
    PlayerStomachDecreaceRate=1.000000,
    PlayerStaminaDecreaceRate=1.000000,
    PlayerAutoHPRegeneRate=1.000000,
    PlayerAutoHpRegeneRateInSleep=1.000000,
    PalStomachDecreaceRate=1.000000,
    PalStaminaDecreaceRate=1.000000,
    PalAutoHPRegeneRate=1.000000,
    PalAutoHpRegeneRateInSleep=1.000000,
    BuildObjectDamageRate=1.000000,
    BuildObjectDeteriorationDamageRate=1.000000,
    CollectionDropRate=1.000000,
    CollectionObjectHpRate=1.000000,
    CollectionObjectRespawnSpeedRate=1.000000,
    EnemyDropItemRate=1.000000,
    DeathPenalty=All,
    bEnablePlayerToPlayerDamage=False,
    bEnableFriendlyFire=False,
    bEnableInvaderEnemy=True,
    bActiveUNKO=False,
    bEnableAimAssistPad=True,
    bEnableAimAssistKeyboard=False,
    DropItemMaxNum=3000,
    DropItemMaxNum_UNKO=100,
    BaseCampMaxNum=128,
    BaseCampWorkerMaxNum=15,
    DropItemAliveMaxHours=1.000000,
    bAutoResetGuildNoOnlinePlayers=False,
    AutoResetGuildTimeNoOnlinePlayers=72.000000,
    GuildPlayerMaxNum=20,
    PalEggDefaultHatchingTime=72.000000,
    WorkSpeedRate=1.000000,
    bIsMultiplay=False,
    bIsPvP=False,
    bCanPickupOtherGuildDeathPenaltyDrop=False,
    bEnableNonLoginPenalty=True,
    bEnableFastTravel=True,
    bIsStartLocationSelectByMap=True,
    bExistPlayerAfterLogout=False,
    bEnableDefenseOtherGuildPlayer=False,
    CoopPlayerMaxNum=4,
    ServerPlayerMaxNum=32,
    ServerName="Palworld Server powered by Kubernetes",
    ServerDescription="",
    AdminPassword="",
    ServerPassword="",
    PublicPort=8211,
    PublicIP="",
    RCONEnabled=False,
    RCONPort=25575,
    Region="",
    bUseAuth=True,
    BanListURL="https://api.palworldgame.com/api/banlist.txt"
    )
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: palworld-server
  name: palworld-server
  namespace: palworld
spec:
  replicas: 1
  serviceName: palworld-server
  selector:
    matchLabels:
      app: palworld-server
  template:
    metadata:
      labels:
        app: palworld-server
    spec:
      containers:
        - name: palworld-server
          image: thijsvanloef/palworld-server-docker@sha256:ae1771981e9b933da5363c2ae02c1f4548404c4be2438670a2351047c0d03eba
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8211
              name: server
              protocol: UDP
            - containerPort: 27015
              name: query
              protocol: UDP
          env:
            - name: SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: palworld-secrets
                  key: serverPassword
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: palworld-secrets
                  key: rconPassword
          envFrom:
            - configMapRef:
                name: palworld-env
          volumeMounts:
            - mountPath: /palworld
              name: data
            - mountPath: /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini
              name: palworld-settings
              subPath: PalWorldSettings.ini
          resources:
            requests:
              cpu: 4000m
              memory: 16Gi
            limits:
              cpu: 6000m
              memory: 32Gi
      volumes:
        - name: palworld-settings
          configMap:
            name: palworld-settings
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOncePod
        storageClassName: iscsi-ssd-storage
        resources:
          requests:
            storage: 30Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: palworld
  annotations:
    metallb.universe.tf/address-pool: palworld-pool
  name: palworld
  namespace: palworld
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  externalTrafficPolicy: Local
  ports:
    - name: server
      port: 8211
      protocol: UDP
      targetPort: server
    - name: query
      port: 27015
      protocol: UDP
      targetPort: query
  selector:
    app: palworld-server
