apiVersion: v1
kind: PersistentVolume
metadata:
  name: palworld-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iscsi-ssd-storage
  claimRef:
    namespace: palworld
    name: data-palworld-server-0
  iscsi:
    targetPortal: 172.16.255.1:3260
    iqn: iqn.2005-10.org.freenas.ctl:palworld
    lun: 0
    fsType: xfs
    readOnly: false
