apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: palworld
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: palworld
          image: thijsvanloef/palworld-server-docker@sha256:ae1771981e9b933da5363c2ae02c1f4548404c4be2438670a2351047c0d03eba
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never
