apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: palworld
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: palworld
          image: thijsvanloef/palworld-server-docker@sha256:1f271625687d70d9400250943651f13391b45dd8abbb16b777189ddb115b01fd
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never
