apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: palworld
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: palworld
          image: thijsvanloef/palworld-server-docker@sha256:d8400308048115e22c178a1bebd475af8d0707282ffee4bb541f8c0452fc2821
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never
