version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker/nextcloud"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "nextcloud"
        update-types:
          - "version-update:semver-major"
  - package-ecosystem: "docker"
    directory: "/kubernetes/nextcloud"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "mariadb"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: "/kubernetes/immich"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "immich-app/postgres"
      - dependency-name: "valkey/valkey"
