version: "3.8"

services:
  #
  # TV
  #
  mirakurun:
    image: akashisn/mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
      LOG_LEVEL: "3"
    devices:
      - /dev/bus:/dev/bus
      - /dev/dvb:/dev/dvb
    volumes:
      - ./mirakurun/run/:/var/run/
      - ./mirakurun/config/:/app-config/
      - ./mirakurun/data/:/app-data/
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m

  mariadb_epgstation:
    image: mariadb:10.5
    volumes:
      - mariadb_epgstation:/var/lib/mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_USER: ${MYSQL_EPGSTATION_USER}
      MYSQL_PASSWORD: ${MYSQL_EPGSTATION_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_EPGSTATION_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_EPGSTATION_DATABASE}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --performance-schema=false --expire_logs_days=1
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  epgstation:
    image: akashisn/epgstation:4.3.2-qsv
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./epgstation/config:/app/config
      - ./epgstation/thumbnail:/app/thumbnail
      - ${RECODED_PATH}:/app/recorded
      - log_volume:/var/promtail
    devices:
      - /dev/dri:/dev/dri
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_USER: ${MYSQL_EPGSTATION_USER}
      MYSQL_PASSWORD: ${MYSQL_EPGSTATION_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_EPGSTATION_DATABASE}
      HOME: /app
    depends_on:
      - mirakurun
      - mariadb_epgstation
    command: >
      /bin/sh -c
        "mkdir -p /var/promtail/epgstation \
        && rm -rf /app/logs \
        && ln -snf /var/promtail/epgstation /app/logs \
        && envsubst \
            '$$MYSQL_USER $$MYSQL_PASSWORD $$MYSQL_DATABASE' \
            < /app/config/config.yml.template \
            > /app/config/config.yml \
        && npm start"
    restart: always

  #
  # Nextcloud
  #

  mariadb_nextcloud:
    image: mariadb:10.5
    volumes:
      - mariadb_nextcloud:/var/lib/mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_USER: ${MYSQL_NEXTCLOUD_USER}
      MYSQL_PASSWORD: ${MYSQL_NEXTCLOUD_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_NEXTCLOUD_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NEXTCLOUD_DATABASE}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --performance-schema=false --expire_logs_days=1
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  redis_nextcloud:
    image: redis:alpine
    volumes:
      - redis_nextcloud:/data
    environment:
      TZ: "Asia/Tokyo"
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    restart: always

  nextcloud:
    image: akashisn/nextcloud
    volumes:
      - nextcloud:/var/www/html
      - ${NAS_PATH}:/mnt
      - log_volume:/var/promtail
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_USER: ${MYSQL_NEXTCLOUD_USER}
      MYSQL_PASSWORD: ${MYSQL_NEXTCLOUD_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_NEXTCLOUD_DATABASE}
      MYSQL_HOST: mariadb_nextcloud
      REDIS_HOST: redis_nextcloud
      REDIS_HOST_PASSWORD: ${REDIS_HOST_PASSWORD}
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${FILES_SUBDOMAIN}.${DOMAIN}
      PHP_MEMORY_LIMIT: 16G
      PHP_UPLOAD_LIMIT: 100G
      NEXTCLOUD_DATA_DIR: /mnt/nextcloud
      OVERWRITEPROTOCOL: https
      TRUSTED_PROXIES: nginx
    depends_on:
      - mariadb_nextcloud
      - redis_nextcloud
    command: >
      /bin/sh -c
        "mkdir -p /var/promtail/nextcloud \
        && /usr/bin/supervisord -c /etc/supervisord.conf"
    restart: always

  #
  # Nginx
  #

  nginx:
    image: akashisn/nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - nextcloud:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - log_volume:/var/promtail
    environment:
      TZ: "Asia/Tokyo"
      TV_SUBDOMAIN: ${TV_SUBDOMAIN}
      FILES_SUBDOMAIN: ${FILES_SUBDOMAIN}
      DOMAIN: ${DOMAIN}
    depends_on:
      - epgstation
      - nextcloud
    ports:
      - "443:443"
    command: >
      /bin/sh -c
        "mkdir -p /var/promtail/nginx \
        && envsubst \
          '$$TV_SUBDOMAIN $$DOMAIN' \
          < /etc/nginx/conf.d/tv.conf.template \
          > /etc/nginx/conf.d/tv.conf \
        && envsubst \
          '$$FILES_SUBDOMAIN $$DOMAIN' \
          < /etc/nginx/conf.d/files.conf.template \
          > /etc/nginx/conf.d/files.conf \
        && envsubst \
          '$$DOMAIN' \
          < /etc/nginx/conf.d/nginx.conf.template \
          > /etc/nginx/nginx.conf \
        && /usr/bin/supervisord -c /etc/supervisord.conf"
    restart: always

  #
  # DNS
  #

  dnsmasq:
    image: akashisn/dnsmasq
    ports:
      - "${LOCAL_IP}:53:53/udp"
    restart: always

  #
  # Samba
  #

  samba:
    image: akashisn/samba
    volumes:
      - ${SAMBA_PATH}:${SAMBA_PATH}
      - log_volume:/var/promtail
    environment:
      TZ: "Asia/Tokyo"
      SAMBA_PASSWORD: ${SAMBA_PASSWORD}
      SAMBA_PATH: ${SAMBA_PATH}
    ports:
      - "139:139"
      - "445:445"
    restart: always

  #
  # Logging tools
  #

  # promtail:
  #   image: grafana/promtail
  #   volumes:
  #     - log_volume:/var/promtail
  #     - ./promtail:/etc/promtail
  #   command: >
  #     -config.file=/etc/promtail/config.yml
  #     -print-config-stderr
  #   depends_on:
  #     - nginx
  #   ports:
  #     - "9080:9080"
  #   restart: always

volumes:
  mariadb_epgstation:
    driver: local
  mariadb_nextcloud:
    driver: local
  redis_nextcloud:
    driver: local
  nextcloud:
    driver: local
  log_volume:
    driver: local
