apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-old-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    namespace: nextcloud-old
    name: app-nextcloud-0
  local:
    path: /pool/nextcloud/nextcloud-app
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k3s-oci
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-old-data-pv
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3ql-storage
  claimRef:
    namespace: nextcloud-old
    name: data-nextcloud-0
  iscsi:
    targetPortal: 100.102.72.106:3260
    iqn: iqn.2005-10.org.freenas.ctl:nextcloud-data
    lun: 0
    fsType: xfs
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-old-mariadb-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    namespace: nextcloud-old
    name: data-nextcloud-mariadb-0
  local:
    path: /pool/nextcloud/nextcloud-mariadb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: storage.nextcloud
            operator: In
            values:
              - "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-old-static-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    namespace: nextcloud-old
    name: static-nextcloud-0
  local:
    path: /pool/nextcloud/static-files
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: storage.nextcloud
            operator: In
            values:
              - "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-old-musics-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-hdd-storage
  claimRef:
    namespace: nextcloud-old
    name: musics-nextcloud-0
  nfs:
    server: truenas
    path: /mnt/ssd/musics
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-old-videos-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-hdd-storage
  claimRef:
    namespace: nextcloud-old
    name: videos-nextcloud-0
  nfs:
    server: truenas
    path: /mnt/hdd/nfs/videos
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-old-photos-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-hdd-storage
  claimRef:
    namespace: nextcloud-old
    name: photos-nextcloud-0
  nfs:
    server: truenas
    path: /mnt/hdd/nfs/photos
  mountOptions:
    - nfsvers=4.2
