apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-cert
  namespace: adguard
spec:
  secretName: adguard-cert
  dnsNames:
    - adguard.dns.akashisn.info
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
