apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard
  namespace: adguard
  labels:
    app: adguard
spec:
  storageClassName: auto-ebs-gp3
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
