apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
  namespace: adguard
spec:
  selector:
    matchLabels:
      app: adguard
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: adguard
    spec:
      containers:
        - name: adguardhome
          image: adguard/adguardhome:v0.107.57
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 53
              protocol: UDP
              name: adguard-dns
            - containerPort: 443
              protocol: TCP
              name: adguard-doh
            - containerPort: 853
              protocol: TCP
              name: adguard-dot
            - containerPort: 3000
              protocol: TCP
              name: adguard-dashboard
          volumeMounts:
            - name: adguardhome-config
              mountPath: /opt/adguardhome/conf
            - name: adguardhome-logs
              mountPath: /opt/adguardhome/work
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "2048Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
      volumes:
        - name: certs
          secret:
            secretName: adguard-cert
        - name: adguardhome-config
          persistentVolumeClaim:
            claimName: adguard
        - name: adguardhome-logs
          emptyDir: {}
