apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: adguard.dns.akashisn.info
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  labels:
    service: adguard
  name: adguard
  namespace: adguard
spec:
  type: LoadBalancer
  loadBalancerClass: eks.amazonaws.com/nlb
  ports:
    - port: 53
      protocol: UDP
      name: adguard-dns
    - port: 443
      protocol: TCP
      name: adguard-doh
    - port: 853
      protocol: TCP
      name: adguard-dot
    - port: 3000
      protocol: TCP
      name: adguard-dashboard
  selector:
    app: adguard
