apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: nextcloud
          image: ghcr.io/akashisn/nextcloud@sha256:559265734552457d66e90037245aa78e36ec4e2f59730225a468a294d895a268
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never