apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: nextcloud
          image: ghcr.io/akashisn/nextcloud@sha256:5dbd5584e9a0f41933a530ace003db808d85fd158036e6f867cbf861c0f59802
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never