apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: nextcloud
          image: ghcr.io/akashisn/nextcloud@sha256:f5af98f78bdc0f1291dae26a1a133a94757105030a7b0633a1873c85fbdb545f
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never