apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: tv
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: envsubst
          image: ghcr.io/akashisn/envsubst@sha256:32cb715670b2f497233819b0e5448d355ddcc1de4dd893ba92c186d33bcd9a7f
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
        - name: mirakc
          image: ghcr.io/akashisn/mirakc@sha256:1246c8c636e0a886e7dba00bae5594c6ac0097e8c1e6a570edb349483ebbb555
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
        - name: epgstation
          image: ghcr.io/akashisn/epgstation@sha256:399347dbc79d81c4ebb872a57a7fe357d30ef2a0cd397193e8734bbc2cb63c59
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never
