apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: tv
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: envsubst
          image: ghcr.io/akashisn/envsubst@sha256:32cb715670b2f497233819b0e5448d355ddcc1de4dd893ba92c186d33bcd9a7f
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
        - name: mirakc
          image: ghcr.io/akashisn/mirakc@sha256:2a21b94804a6591eba2dd700d69c731760990a343826fa4bd152875adf38db47
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
        - name: epgstation
          image: ghcr.io/akashisn/epgstation@sha256:f43e8eef3526c222b1e4f3b30dbe0a10615fc26ab6122968a4d358f68f89a2ac
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never
