apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-env
  namespace: immich
data:
  TZ: "Asia/Tokyo"
  IMMICH_ENV: production
  IMMICH_HOST: "0.0.0.0"
  IMMICH_PORT: "2283"
  IMMICH_TRUSTED_PROXIES: immich-server
  DB_HOSTNAME: immich-postgres
  DB_PORT: "5432"
  DB_USERNAME: postgres
  DB_PASSWORD_FILE: /secrets/immich_postgres_user_password
  DB_DATABASE_NAME: immich
  DB_VECTOR_EXTENSION: pgvecto.rs
  REDIS_HOSTNAME: immich-redis
  REDIS_PORT: "6379"
