apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: immich-microservices
  name: immich-microservices
  namespace: immich
spec:
  replicas: 2
  selector:
    matchLabels:
      app: immich-microservices
  template:
    metadata:
      labels:
        app: immich-microservices
    spec:
      containers:
        - name: immich-microservices
          image: ghcr.io/immich-app/immich-server:v1.122.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: immich-env
          env:
            - name: IMMICH_WORKERS_EXCLUDE
              value: api
          volumeMounts:
            - name: immich-photos
              mountPath: /usr/src/app/upload
            - name: immich-secrets
              mountPath: /secrets
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 2000m
              memory: 2000Mi
      volumes:
        - name: immich-secrets
          projected:
            sources:
              - secret:
                  name: immich-secrets
        - name: immich-photos
          persistentVolumeClaim:
            claimName: immich-photos-pvc
