---
# file: roles/common/tasks/crio.yml
- name: Add CRI-O apt keyrings
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{ k8s_major_version }}/deb/Release.key"
    dest: "/etc/apt/keyrings/cri-o-apt-keyring.asc"
    mode: "0644"
  become: true

- name: Add CRI-O repositories
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.asc] https://pkgs.k8s.io/addons:/cri-o:/stable:/v{{ k8s_major_version }}/deb/ /"
    filename: "/etc/apt/sources.list.d/cri-o.list"
    state: present
  become: true

- name: Install CRI-O
  ansible.builtin.apt:
    name:
      - cri-o
    state: present
    update_cache: true
  become: true

- name: Hold cri-o packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - cri-o
  become: true

- name: Copy crio-ulimits.conf configuration
  ansible.builtin.copy:
    src: crio-ulimits.conf
    dest: /etc/crio/crio.conf.d/20-ulimits.conf
    mode: "0644"
  become: true

- name: Enable and start crio service
  ansible.builtin.systemd:
    name: crio
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
