---
# file: roles/common/tasks/helm.yml
- name: Install helm
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl -sfL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash -s -
    executable: /bin/bash
  changed_when: true

- name: Install helm diff
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      helm plugin install https://github.com/databus23/helm-diff
    executable: /bin/bash
  register: helm_diff_result
  ignore_errors: true
  changed_when: "'helm-diff installed into' in helm_diff_result.stdout"

- name: Upgrade helm diff
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      helm plugin upgrade diff
    executable: /bin/bash
  changed_when: "'helm-diff installed into' in helm_diff_result.stdout"
