apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-env
  namespace: minecraft
data:
  TZ: "Asia/Tokyo"
  EULA: "TRUE"
  MEMORY: "16G"
  MOTD: "A Minecraft server powered by §nKubernetes§r"
  DIFFICULTY: "normal"
  TYPE: AUTO_CURSEFORGE
  VERSION: "1.20.1"
  FORGE_VERSION: "47.2.20"
  CF_SLUG: all-the-mods-9
  CF_FILE_ID: "5458414"
  RCON_PASSWORD_FILE: "/secrets/minecraft_rcon_password"
  OVERRIDE_SERVER_PROPERTIES: "TRUE"
  WHITELIST_FILE: "/secrets/minecraft_whitelist"
  ENABLE_WHITELIST: "TRUE"
  ENFORCE_WHITELIST: "TRUE"
  OVERRIDE_WHITELIST: "TRUE"
  ALLOW_FLIGHT: "TRUE"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minecraft
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  serviceName: minecraft
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      nodeSelector:
        kubernetes.io/hostname: worker-node-02
      containers:
        - name: minecraft
          image: itzg/minecraft-server@sha256:34898750426828b5a8e7da06bc6c478a322d80c26848bffdc95b5d5b031c5f90
          imagePullPolicy: IfNotPresent
          command: [ "/bin/sh", "-c", "sed -i '/jei/d' /image/cf-exclude-include.json && /start" ] # TODO FIX
          ports:
          - containerPort: 25565
            name: minecraft
          envFrom:
          - configMapRef:
              name: minecraft-env
          env:
          - name: CF_API_KEY
            valueFrom:
              secretKeyRef:
                name: minecraft-secrets
                key: minecraft_cf_api_key
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /backup
              name: backup
            - mountPath: /secrets
              name: minecraft-secrets
          readinessProbe:
            exec:
              command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost" ]
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            exec:
              command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost"]
            initialDelaySeconds: 120
            periodSeconds: 60
          resources:
            requests:
              cpu: 4000m
              memory: 16Gi
            limits:
              cpu: 8000m
              memory: 24Gi
      volumes:
        - name: minecraft-secrets
          secret:
            secretName: minecraft-secrets
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOncePod
      storageClassName: iscsi-ssd-storage
      resources:
        requests:
          storage: 50Gi
  - metadata:
      name: backup
    spec:
      accessModes:
      - ReadWriteOncePod
      storageClassName: nfs-hdd-storage
      resources:
        requests:
          storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: minecraft
  annotations:
    metallb.universe.tf/address-pool: minecraft-pool
  name: minecraft
  namespace: minecraft
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 25565
    name: minecraft
  selector:
    app: minecraft
