apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iscsi-ssd-storage
  claimRef:
    namespace: minecraft
    name: data-minecraft-0
  iscsi:
    targetPortal: 172.16.255.1:3260
    iqn: iqn.2005-10.org.freenas.ctl:minecraft
    lun: 0
    fsType: xfs
    readOnly: false
