apiVersion: v1
kind: Secret
metadata:
  name: vso-secrets
  namespace: minecraft
  annotations:
    replicator.v1.mittwald.de/replicate-from: vault-secrets-operator/vso-secrets
type: Opaque
data: {}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: minecraft-secrets
  namespace: minecraft
spec:
  appName: minecraft
  refreshAfter: 48h
  hcpAuthRef: vault-secrets-operator/hcp-auth
  destination:
    create: true
    name: minecraft-secrets
