apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-env
  namespace: nextcloud
data:
  TZ: "Asia/Tokyo"
  NEXTCLOUD_ADMIN_USER_FILE: /secrets/nextcloud_admin_user
  NEXTCLOUD_ADMIN_PASSWORD_FILE: /secrets/nextcloud_admin_password
  NEXTCLOUD_DATA_DIR: /mnt/nextcloud
  OVERWRITEPROTOCOL: https
  NEXTCLOUD_TRUSTED_DOMAINS: files.akashisn.info
  MYSQL_HOST: nextcloud-mariadb
  MYSQL_USER: nextcloud
  MYSQL_DATABASE: nextcloud
  MYSQL_PASSWORD_FILE: /secrets/nextcloud_mariadb_user_password
  REDIS_HOST: nextcloud-redis
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_SECURE: tls
  MAIL_FROM_ADDRESS: no-reply
  MAIL_DOMAIN: files.localhost
  SMTP_PASSWORD_FILE: /secrets/smtp_password
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 1
  serviceName: nextcloud
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: nextcloud
          image: ghcr.io/akashisn/nextcloud@sha256:dfc17885f4bef6bf999f959bcfe710414cfa3aaf3442aeb1b5c69a8fc64bf8c0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: nextcloud-env
          env:
            - name: SMTP_NAME
              valueFrom:
                secretKeyRef:
                  name: common-secrets
                  key: email_address
          volumeMounts:
            - name: app
              mountPath: /var/www/html
            - name: data
              mountPath: /mnt/nextcloud
            - name: static
              mountPath: /mnt/static
            - name: musics
              mountPath: /mnt/musics
            - name: videos
              mountPath: /mnt/videos
            - name: photos
              mountPath: /mnt/photos
            - name: nextcloud-secrets
              mountPath: /secrets
            - name: nextcloud-conf
              mountPath: /usr/local/etc/php-fpm.d/zz-docker.conf
              subPath: zz-docker.conf
              readOnly: true
            - name: nextcloud-conf
              mountPath: /usr/local/etc/php/conf.d/nextcloud.ini
              subPath: nextcloud.ini
              readOnly: true
            - name: nextcloud-hooks
              mountPath: /docker-entrypoint-hooks.d/before-starting/config.sh
              subPath: config.sh
              readOnly: true
          resources:
            requests:
              cpu: 300m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 2000Mi
        - name: nginx
          image: nginx:1.29.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: nginx-nextcloud
            - containerPort: 8080
              name: nginx-static
          volumeMounts:
            - name: app
              mountPath: /var/www/html
            - name: static
              mountPath: /mnt/static
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/nextcloud.conf
              subPath: nextcloud.conf
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/static.conf
              subPath: static.conf
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 1000Mi
            limits:
              cpu: 500m
              memory: 2000Mi
      volumes:
        - name: nextcloud-secrets
          projected:
            sources:
              - secret:
                  name: nextcloud-secrets
              - secret:
                  name: common-secrets
        - name: nextcloud-conf
          configMap:
            name: nextcloud-conf
        - name: nextcloud-hooks
          configMap:
            defaultMode: 504
            name: nextcloud-hooks
        - name: nginx-conf
          configMap:
            name: nginx-conf
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  volumeClaimTemplates:
    - metadata:
        name: app
      spec:
        accessModes:
          - ReadWriteOncePod
        storageClassName: local-storage
        resources:
          requests:
            storage: 30Gi
    - metadata:
        name: static
      spec:
        accessModes:
          - ReadWriteOncePod
        storageClassName: local-storage
        resources:
          requests:
            storage: 30Gi
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOncePod
        storageClassName: iscsi-hdd-storage
        resources:
          requests:
            storage: 8Ti
    - metadata:
        name: musics
      spec:
        accessModes:
          - ReadWriteOncePod
        storageClassName: nfs-hdd-storage
        resources:
          requests:
            storage: 500Gi
    - metadata:
        name: videos
      spec:
        accessModes:
          - ReadWriteOncePod
        storageClassName: nfs-hdd-storage
        resources:
          requests:
            storage: 2Ti
    - metadata:
        name: photos
      spec:
        accessModes:
          - ReadWriteOncePod
        storageClassName: nfs-hdd-storage
        resources:
          requests:
            storage: 2Ti
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: nextcloud
  name: nextcloud
  namespace: nextcloud
spec:
  ports:
    - name: nginx-nextcloud
      port: 80
      targetPort: nginx-nextcloud
    - name: nginx-static
      port: 8080
      targetPort: nginx-static
  selector:
    app: nextcloud
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nextcloud
  namespace: nextcloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.akashisn.info
        - static.akashisn.info
      secretName: nextcloud-cert
  rules:
    - host: files.akashisn.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  name: nginx-nextcloud
    - host: static.akashisn.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  name: nginx-static
