appenders:
  system:
    type: dateFile
    backups: 31
    filename: "%EPGUpdaterSystem%"
    pattern: "-yyyy-MM-dd"
  access:
    type: dateFile
    backups: 31
    filename: "%EPGUpdaterAccess%"
    pattern: "-yyyy-MM-dd"
  stream:
    type: dateFile
    backups: 31
    filename: "%EPGUpdaterStream%"
    pattern: "-yyyy-MM-dd"
  encode:
    type: dateFile
    backups: 31
    filename: "%EPGUpdaterEncode%"
    pattern: "-yyyy-MM-dd"
  console:
    type: console
  stdout:
    type: stdout
categories:
  default:
    appenders:
      - console
      - stdout
    level: info
  system:
    appenders:
      - system
      - stdout
    level: info
  access:
    appenders:
      - access
      - stdout
    level: info
  stream:
    appenders:
      - stream
      - stdout
    level: info