---
# file: roles/cluster/tasks/cert-manager.yml
- name: Add jetstack Helm charts repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
  become: false

- name: Deploy cert-manager chart using set values on target
  kubernetes.core.helm:
    release_name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: "1.17.*"
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: true
    wait: true
    atomic: true
    release_values:
      installCRDs: true
  become: false

- name: Create a cert-manager secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare-api-token-secret
        namespace: cert-manager
      type: Opaque
      stringData:
        api-token: "{{ cloudflare_token }}"
  become: false

- name: Create a cert-manager ClusterIssuer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-cluster-issuer
      spec:
        acme:
          server: "{{ acme_v2_url[target_env] }}"
          preferredChain: ISRG Root X1
          email: "{{ email }}"
          privateKeySecretRef:
            name: acme-client-letsencrypt
          solvers:
            - dns01:
                cloudflare:
                  apiTokenSecretRef:
                    name: cloudflare-api-token-secret
                    key: api-token
  become: false
