---
# file: roles/cluster/tasks/main.yml
- name: Setup cluster
  become: false
  block:
    - name: Import helm.yml
      ansible.builtin.import_tasks:
        file: helm.yml

    - name: Import ingress-nginx.yml
      ansible.builtin.import_tasks:
        file: ingress-nginx.yml

    - name: Import cert-manager.yml
      ansible.builtin.import_tasks:
        file: cert-manager.yml

    - name: Import argo-cd.yml
      ansible.builtin.import_tasks:
        file: argo-cd.yml

    - name: Import secrets.yml
      ansible.builtin.import_tasks:
        file: secrets.yml

    - name: Create the storage class
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../kubernetes/storage-class.yml') | from_yaml_all }}"
      become: false

- name: Wait for all pods to be ready
  ansible.builtin.command:
    cmd: kubectl get pods -A -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}'
  register: result
  until: result.stdout.find("False") == -1
  retries: 60
  delay: 10
  changed_when: false
  become: false
