---
# file: roles/cluster/tasks/secrets.yml
- name: Create namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
  loop:
    - nextcloud
    - immich
  become: false

- name: Create the immich/immich-secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: immich-secrets
        namespace: immich
      type: Opaque
      data:
        immich_postgres_user_password: "{{ immich_postgres_user_password | b64encode }}"
  become: false

- name: Create the nextcloud/nextcloud-secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: nextcloud-secrets
        namespace: nextcloud
      type: Opaque
      data:
        email_address: "{{ nextcloud_email_address | b64encode }}"
        smtp_password: "{{ nextcloud_smtp_password | b64encode }}"
        admin_user: "{{ nextcloud_admin_user | b64encode }}"
        admin_password: "{{ nextcloud_admin_password | b64encode }}"
        postgres_password: "{{ nextcloud_postgres_password | b64encode }}"
        oidc_issuer: "{{ nextcloud_oidc_issuer | b64encode }}"
        oidc_client_id: "{{ nextcloud_oidc_client_id | b64encode }}"
        oidc_client_secret: "{{ nextcloud_oidc_client_secret | b64encode }}"
  become: false
