---
# file: roles/cluster/tasks/metallb.yml
- name: Create namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
  loop:
    - nextcloud
    - immich
  become: false

- name: Create the immich/immich-secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: immich-secrets
        namespace: immich
      type: Opaque
      data:
        immich_postgres_user_password: "{{ immich_postgres_user_password | b64encode }}"
  become: false

- name: Create the nextcloud/common-secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: common-secrets
        namespace: nextcloud
      type: Opaque
      data:
        email_address: "{{ email_address | b64encode }}"
        smtp_password: "{{ smtp_password | b64encode }}"
  become: false

- name: Create the nextcloud/nextcloud-secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: nextcloud-secrets
        namespace: nextcloud
      type: Opaque
      data:
        nextcloud_mariadb_root_password: "{{ nextcloud_mariadb_root_password | b64encode }}"
        nextcloud_mariadb_user_password: "{{ nextcloud_mariadb_user_password | b64encode }}"
        nextcloud_admin_user: "{{ nextcloud_admin_user | b64encode }}"
        nextcloud_admin_password: "{{ nextcloud_admin_password | b64encode }}"
  become: false
