virtualmachines:
  children:
    master:
      hosts:
        master-node:
          ansible_host: k8s-control-plane
        microk8s:
          ansible_host: microk8s
    worker:
      hosts:
        worker-node01:
          ansible_host: worker-node