virtualmachines:
  children:
    master:
      hosts:
        master-node:
          ansible_host: k8s-control-plane
        k3s:
          ansible_host: k3s
    worker:
      hosts:
        worker-node01:
          ansible_host: worker-node