---
# file: setup-cluster.yml
- name: Setup common for kubeadm
  hosts: virtualmachines
  roles:
    - role: variable
      when: inventory_hostname != "microk8s"
    - role: common
      vars:
        os: "xUbuntu_22.04"
        k8s_major_version: "1.28"
      when: inventory_hostname != "microk8s"

- name: Setup cluster by kubeadm
  hosts: virtualmachines
  roles:
    - role: variable
      when: inventory_hostname != "microk8s"
    - role: cluster
      vars:
        target_env: "production" # staging or production
      when: inventory_hostname != "microk8s"
