apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-env
  namespace: minecraft
data:
  TZ: "Asia/Tokyo"
  EULA: "TRUE"
  MEMORY: "16G"
  MOTD: "A §l§cVanilla§r Minecraft server powered by §nKubernetes§r"
  DIFFICULTY: "normal"
  RCON_PASSWORD_FILE: "/secrets/minecraft_rcon_password"
  OVERRIDE_SERVER_PROPERTIES: "TRUE"
  ENABLE_WHITELIST: "TRUE"
  ENFORCE_WHITELIST: "TRUE"
  OVERRIDE_WHITELIST: "TRUE"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minecraft-vanilla
  name: minecraft-vanilla
  namespace: minecraft
spec:
  replicas: 1
  serviceName: minecraft-vanilla
  selector:
    matchLabels:
      app: minecraft-vanilla
  template:
    metadata:
      labels:
        app: minecraft-vanilla
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          imagePullPolicy: Always
          ports:
          - containerPort: 25565
            name: minecraft
          envFrom:
          - configMapRef:
              name: minecraft-env
          env:
          - name: WHITELIST
            valueFrom:
              secretKeyRef:
                name: minecraft-whitelist
                key: minecraft_whitelist
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /secrets
              name: minecraft-secrets
          readinessProbe:
            exec:
              command: [ "/usr/local/bin/mc-monitor", "status", "--host", "localhost" ]
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            exec:
              command: ["/usr/local/bin/mc-monitor", "status", "--host", "localhost"]
            initialDelaySeconds: 120
            periodSeconds: 60
        # - name: backup
        #   image: itzg/mc-backup
        #   securityContext:
        #     runAsUser: 1000
        #   env:
        #     - name: BACKUP_INTERVAL
        #       value: "60"
        #     - name: INITIAL_DELAY
        #       value: "10"
        #   volumeMounts:
        #     - mountPath: /data
        #       name: data
        #       readOnly: true
        #     - mountPath: /backups
        #       name: backups
      volumes:
        - name: minecraft-secrets
          secret:
            secretName: minecraft-secrets
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: iscsi-ssd-storage
      resources:
        requests:
          storage: 30Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: minecraft-vanilla
  name: minecraft-vanilla
  namespace: minecraft
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.254.25
  ports:
  - port: 25565
    name: minecraft
  selector:
    app: minecraft-vanilla
