apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: nextcloud
          image: ghcr.io/akashisn/nextcloud@sha256:09864971958b62fae01a870540c18c8fdef67ccb0210dd841e1b28b3295990d2
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never