apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: nextcloud
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: nextcloud
          image: ghcr.io/akashisn/nextcloud@sha256:9e833d98f1952118a4e0110582d360ac53011b3d0e088fb5b2d7917914321263
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never