---
# file: roles/cluster/tasks/dex.yml
- name: Add dex Helm charts repository
  kubernetes.core.helm_repository:
    name: dex
    repo_url: https://charts.dexidp.io
  become: false

- name: Deploy dex chart using set values on target
  kubernetes.core.helm:
    release_name: dex
    chart_ref: dex/dex
    chart_version: "0.17.*"
    release_namespace: auth
    update_repo_cache: true
    wait: true
    atomic: true
    values: "{{ lookup('template', 'dex-values.yml.j2') | from_yaml }}"
  become: false
