apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: nfs-hdd-storage
