apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: wordpress
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: wordpress
          image: ghcr.io/akashisn/wordpress@sha256:972bc6a1b36b9ddd2fcc4b7230376bb0f3681bde3fe0f8fc45e6fc37944b4c34
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never