apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry
  namespace: registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-exec
  namespace: registry
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry
  namespace: registry
subjects:
  - kind: ServiceAccount
    name: registry
    namespace: registry
roleRef:
  kind: Role
  name: registry-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: registry-cronjob
  namespace: registry
spec:
  concurrencyPolicy: Forbid
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: registry
          containers:
            - name: kubectl
              image: ghcr.io/akashisn/kubectl@sha256:dac53e4656962da663dd0ee5d6aad4e997109588d59e763604b5aa742bc41ac6
              imagePullPolicy: IfNotPresent
              args:
                [
                  "exec",
                  "-n",
                  "registry",
                  "registry-0",
                  "-c",
                  "registry",
                  "--",
                  "/bin/sh",
                  "-c",
                  'registry garbage-collect /etc/docker/registry/config.yml',
                ]
          restartPolicy: Never
