# domain
domain: "akashisn.info"
# k3s node labels
k3s_node_labels:
  - storage.immich=true
  - storage.nextcloud=true
# acme
cloudflare_token: "{{ vault_cloudflare_token }}"
email: "{{ vault_email }}"
# argo-cd
argocd_fqdn: "argocd.{{ domain }}"
argocd_oidc_issuer: "{{ vault_argocd_oidc_issuer }}"
argocd_oidc_client_id: "{{ vault_argocd_oidc_client_id }}"
argocd_oidc_client_secret: "{{ vault_argocd_oidc_client_secret }}"
argocd_webhook_github_secret: "{{ vault_argocd_webhook_github_secret }}"
# s3ql
s3ql_access_key_id: "{{ vault_s3ql_access_key_id }}"
s3ql_secret_access_key: "{{ vault_s3ql_secret_access_key }}"
s3ql_region: "ap-northeast-1"
s3ql_bucket: "{{ vault_s3ql_bucket }}"
s3ql_filesystems:
  - name: immich
    description: Immich
    storage_url: "s3://{{ s3ql_region }}/{{ s3ql_bucket }}/immich/"
    mount_point: /mnt/s3ql/immich
    fs_passphrase: "{{ vault_immich_s3ql_fs_passphrase }}"
  - name: nextcloud
    description: Nextcloud
    storage_url: "s3://{{ s3ql_region }}/{{ s3ql_bucket }}/nextcloud/"
    mount_point: /mnt/s3ql/nextcloud
    fs_passphrase: "{{ vault_nextcloud_s3ql_fs_passphrase }}"


#
# Secrets
#

# immich
immich_postgres_user_password: "{{ vault_immich_postgres_user_password }}"

# nextcloud
nextcloud_email_address: "{{ vault_nextcloud_email_address }}"
nextcloud_smtp_password: "{{ vault_nextcloud_smtp_password }}"
nextcloud_admin_user: "{{ vault_nextcloud_admin_user }}"
nextcloud_admin_password: "{{ vault_nextcloud_admin_password }}"
nextcloud_postgres_password: "{{ vault_nextcloud_postgres_password }}"
nextcloud_oidc_issuer: "{{ vault_nextcloud_oidc_issuer }}"
nextcloud_oidc_client_id: "{{ vault_nextcloud_oidc_client_id }}"
nextcloud_oidc_client_secret: "{{ vault_nextcloud_oidc_client_secret }}"
