# domain
domain: "akashisn.info"
# k3s node labels
k3s_node_labels:
  - storage.immich=true
  - storage.nextcloud=true
# acme
cloudflare_token: "{{ vault_cloudflare_token }}"
email: "{{ vault_email }}"
# oauth2-proxy
oauth2_proxy_fqdn: "auth.{{ domain }}"
oauth2_proxy_cloudflare_issuer: "{{ vault_oauth2_proxy_cloudflare_issuer }}"
oauth2_proxy_cloudflare_client_id: "{{ vault_oauth2_proxy_cloudflare_client_id }}"
oauth2_proxy_cloudflare_client_secret: "{{ vault_oauth2_proxy_cloudflare_client_secret }}"
oauth2_proxy_cookie_secret: "{{ vault_oauth2_proxy_cookie_secret }}"
# argo-cd
argocd_fqdn: "argocd.{{ domain }}"
argocd_cloudflare_issuer: "{{ vault_argocd_cloudflare_issuer }}"
argocd_cloudflare_client_id: "{{ vault_argocd_cloudflare_client_id }}"
argocd_cloudflare_client_secret: "{{ vault_argocd_cloudflare_client_secret }}"
argocd_webhook_github_secret: "{{ vault_argocd_webhook_github_secret }}"
# s3ql
s3ql_access_key_id: "{{ vault_s3ql_access_key_id }}"
s3ql_secret_access_key: "{{ vault_s3ql_secret_access_key }}"
s3ql_region: "ap-northeast-1"
s3ql_bucket: "{{ vault_s3ql_bucket }}"
s3ql_filesystems:
  - name: immich
    description: Immich photos
    storage_url: "s3://{{ s3ql_region }}/{{ s3ql_bucket }}/immich/"
    mount_point: /mnt/s3ql/immich-photos
    fs_passphrase: "{{ vault_immich_s3ql_fs_passphrase }}"
  - name: nextcloud
    description: Nextcloud data
    storage_url: "s3://{{ s3ql_region }}/{{ s3ql_bucket }}/nextcloud/"
    mount_point: /mnt/s3ql/nextcloud-data
    fs_passphrase: "{{ vault_nextcloud_s3ql_fs_passphrase }}"


#
# Secrets
#

# common
email_address: "{{ vault_email_address }}"
smtp_password: "{{ vault_smtp_password }}"

# immich
immich_postgres_user_password: "{{ vault_immich_postgres_user_password }}"

# nextcloud
nextcloud_mariadb_root_password: "{{ vault_nextcloud_mariadb_root_password }}"
nextcloud_mariadb_user_password: "{{ vault_nextcloud_mariadb_user_password }}"
nextcloud_admin_user: "{{ vault_nextcloud_admin_user }}"
nextcloud_admin_password: "{{ vault_nextcloud_admin_password }}"
