apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-conf
  namespace: dns
data:
  dnsmasq.conf: |
    port=10053
    cache-size=0
    no-resolv
    server=1.0.0.1
    server=1.1.1.1
    strict-order
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsdist-conf
  namespace: dns
data:
  dnsdist.conf: |
    setACL("0.0.0.0/0")
    addACL("::/0")
    newServer("127.0.0.1:10053")
    addLocal("0.0.0.0:53")
    addLocal("[::]:53")
    addDOHLocal("0.0.0.0:443", "/certs/tls.crt", "/certs/tls.key", "/")
    addDOHLocal("[::]:443", "/certs/tls.crt", "/certs/tls.key", "/")
    addTLSLocal("0.0.0.0:853", "/certs/tls.crt", "/certs/tls.key")
    addTLSLocal("[::]:853", "/certs/tls.crt", "/certs/tls.key")
