virtualmachines:
  children:
    master:
      hosts:
        master-node:
          ansible_host: k8s-control-plane
        k3s:
          ansible_host: k3s
        k3s-vps:
          ansible_host: k3s-vps
    worker:
      hosts:
        worker-node01:
          ansible_host: worker-node-01
        worker-node02:
          ansible_host: worker-node-02