apiVersion: v1
kind: ConfigMap
metadata:
  name: mirakc-conf
  namespace: tv
data:
  config.yml: |
    epg:
      cache-dir: /var/lib/mirakc/epg

    server:
      # Replace `localhost` with `0.0.0.0` (ipv4) or `::` (ipv6) if you like to
      # connect from other hosts.
      addrs:
        - http: '0.0.0.0:40772'

    # from scan_channel.sh
    channels:
      - name: 'Ｊ：ＣＯＭテレビ'
        type: 'GR'
        channel: '13'
        extra-args: ''
        disabled: false

      - name: 'テレ玉１'
        type: 'GR'
        channel: '15'
        extra-args: ''
        disabled: false

      - name: 'ｔｖｋ１'
        type: 'GR'
        channel: '18'
        extra-args: ''
        disabled: false

      - name: 'Ｊ：ＣＯＭチャンネル'
        type: 'GR'
        channel: '19'
        extra-args: ''
        disabled: false

      - name: 'ＴＯＫＹＯ　ＭＸ１'
        type: 'GR'
        channel: '20'
        extra-args: ''
        disabled: false

      - name: 'フジテレビ'
        type: 'GR'
        channel: '21'
        extra-args: ''
        disabled: false

      - name: 'ＴＢＳ１'
        type: 'GR'
        channel: '22'
        extra-args: ''
        disabled: false

      - name: 'テレビ東京１'
        type: 'GR'
        channel: '23'
        extra-args: ''
        disabled: false

      - name: 'テレビ朝日'
        type: 'GR'
        channel: '24'
        extra-args: ''
        disabled: false

      - name: '日テレ１'
        type: 'GR'
        channel: '25'
        extra-args: ''
        disabled: false

      - name: 'ＮＨＫＥテレ１東京'
        type: 'GR'
        channel: '26'
        extra-args: ''
        disabled: false

      - name: 'ＮＨＫ総合１・東京'
        type: 'GR'
        channel: '27'
        extra-args: ''
        disabled: false

      - name: 'ＢＳ朝日１'
        type: 'BS'
        channel: 'BS01_0'
        extra-args: ''
        disabled: false

      - name: 'ＢＳ－ＴＢＳ'
        type: 'BS'
        channel: 'BS01_1'
        extra-args: ''
        disabled: false

      - name: 'ＢＳテレ東'
        type: 'BS'
        channel: 'BS01_2'
        extra-args: ''
        disabled: false

      - name: 'ＷＯＷＯＷプライム'
        type: 'BS'
        channel: 'BS03_0'
        extra-args: ''
        disabled: false

      - name: 'ＮＨＫ'
        type: 'BS'
        channel: 'BS03_1'
        extra-args: ''
        disabled: false

      - name: 'ＷＯＷＯＷライブ'
        type: 'BS'
        channel: 'BS05_0'
        extra-args: ''
        disabled: false

      - name: 'ＷＯＷＯＷシネマ'
        type: 'BS'
        channel: 'BS05_1'
        extra-args: ''
        disabled: false

      - name: 'ＢＳ１１イレブン'
        type: 'BS'
        channel: 'BS09_0'
        extra-args: ''
        disabled: false

      - name: 'スターチャンネル１'
        type: 'BS'
        channel: 'BS09_1'
        extra-args: ''
        disabled: false

      - name: 'ＢＳ１２トゥエルビ'
        type: 'BS'
        channel: 'BS09_2'
        extra-args: ''
        disabled: false

      - name: '放送大学テレビ'
        type: 'BS'
        channel: 'BS11_0'
        extra-args: ''
        disabled: false

      - name: 'ＢＳ釣りビジョン'
        type: 'BS'
        channel: 'BS11_1'
        extra-args: ''
        disabled: false

      - name: 'ＢＳ日テレ'
        type: 'BS'
        channel: 'BS13_0'
        extra-args: ''
        disabled: false

      - name: 'ＢＳフジ・１８１'
        type: 'BS'
        channel: 'BS13_1'
        extra-args: ''
        disabled: false

      - name: 'ＢＳアニマックス'
        type: 'BS'
        channel: 'BS13_2'
        extra-args: ''
        disabled: false

      - name: 'スターチャンネル２'
        type: 'BS'
        channel: 'BS15_0'
        extra-args: ''
        disabled: false

      - name: 'Ｊ　ＳＰＯＲＴＳ　４'
        type: 'BS'
        channel: 'BS19_0'
        extra-args: ''
        disabled: false

      - name: 'Ｊ　ＳＰＯＲＴＳ　１'
        type: 'BS'
        channel: 'BS19_1'
        extra-args: ''
        disabled: false

      - name: 'Ｊ　ＳＰＯＲＴＳ　２'
        type: 'BS'
        channel: 'BS19_2'
        extra-args: ''
        disabled: false

      - name: 'Ｊ　ＳＰＯＲＴＳ　３'
        type: 'BS'
        channel: 'BS19_3'
        extra-args: ''
        disabled: false

      - name: 'ＷＯＷＯＷプラス'
        type: 'BS'
        channel: 'BS21_0'
        extra-args: ''
        disabled: false

      - name: '日本映画専門ｃｈ'
        type: 'BS'
        channel: 'BS21_1'
        extra-args: ''
        disabled: false

      - name: 'グリーンチャンネル'
        type: 'BS'
        channel: 'BS21_2'
        extra-args: ''
        disabled: false

      - name: 'ディズニーｃｈ'
        type: 'BS'
        channel: 'BS23_0'
        extra-args: ''
        disabled: false

      - name: 'ＢＳよしもと'
        type: 'BS'
        channel: 'BS23_1'
        extra-args: ''
        disabled: false

      - name: 'ＢＳＪａｐａｎｅｘｔ'
        type: 'BS'
        channel: 'BS23_2'
        extra-args: ''
        disabled: false

      - name: 'ＢＳ松竹東急'
        type: 'BS'
        channel: 'BS23_3'
        extra-args: ''
        disabled: false

    tuners:
      - name: DDMaxM4-0
        types:
          - GR
          - BS
        command: dvbv5-zap -a 0 -c /usr/local/etc/dvbv5/dvbv5_channels_isdb.conf -r -P {{{channel}}} -o -

      - name: DDMaxM4-1
        types:
          - GR
          - BS
        command: dvbv5-zap -a 1 -c /usr/local/etc/dvbv5/dvbv5_channels_isdb.conf -r -P {{{channel}}} -o -

      - name: DDMaxM4-2
        types:
          - GR
          - BS
        command: dvbv5-zap -a 2 -c /usr/local/etc/dvbv5/dvbv5_channels_isdb.conf -r -P {{{channel}}} -o -

      - name: DDMaxM4-3
        types:
          - GR
          - BS
        command: dvbv5-zap -a 3 -c /usr/local/etc/dvbv5/dvbv5_channels_isdb.conf -r -P {{{channel}}} -o -

    filters:
      decode-filter:
        command: arib-b25-stream
