---
# file: roles/vpn/tasks/main.yml
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest # noqa package-latest
    update_cache: true
  become: true

- name: SoftEtherVPN
  ansible.builtin.import_tasks:
    file: softether.yml
