---
# file: roles/vpn/tasks/softether.yml
- name: Install build dependency packages
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - libncurses5-dev
      - libreadline-dev
      - libsodium-dev
      - libssl-dev
      - pkg-config
      - zlib1g-dev
    state: present
    update_cache: true
  become: true

- name: Check if vpncmd is available
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      command -v vpncmd
    executable: /bin/bash
  register: vpncmd_check
  ignore_errors: true
  changed_when: false

- name: Download and unarchive SoftEtherVPN source
  ansible.builtin.unarchive:
    src: "https://github.com/SoftEtherVPN/SoftEtherVPN/releases/download/{{ softether_version }}/SoftEtherVPN-{{ softether_version }}.tar.xz"
    dest: "/opt/"
    mode: "0644"
    remote_src: true
  when: vpncmd_check.rc != 0
  become: true

- name: Copy softether-build.sh.j2 script template
  ansible.builtin.template:
    src: softether-build.sh.j2
    dest: /opt/softether-build.sh
    mode: "0755"
  when: vpncmd_check.rc != 0
  become: true

- name: Run a build script
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      /opt/softether-build.sh
    executable: /bin/bash
  when: vpncmd_check.rc != 0
  changed_when: true
  become: true
