- name: ＮＨＫＥテレ
  type: GR
  channel: '13'
- name: 読売テレビ
  type: GR
  channel: '14'
- name: ＡＢＣテレビ
  type: GR
  channel: '15'
- name: ＭＢＳ毎日放送
  type: GR
  channel: '16'
- name: 関西テレビ
  type: GR
  channel: '17'
- name: テレビ大阪
  type: GR
  channel: '18'
- name: ＮＨＫ総合
  type: GR
  channel: '24'
- name: サンテレビ
  type: GR
  channel: '26'
- name: BS朝日
  type: BS
  channel: BS01_0
  serviceId: 151
- name: BS朝日 (sub)
  type: BS
  channel: BS01_0
  serviceId: 152
- name: BS-TBS
  type: BS
  channel: BS01_1
  serviceId: 161
- name: BSジャパン
  type: BS
  channel: BS01_2
  serviceId: 171
- name: WOWOWプライム
  type: BS
  channel: BS03_0
  serviceId: 191
  isDisabled: false
- name: NHK BSプレミアム
  type: BS
  channel: BS03_1
  serviceId: 103
- name: NHK BSプレミアム (sub)
  type: BS
  channel: BS03_1
  serviceId: 104
- name: ディズニー・チャンネル
  type: BS
  channel: BS03_2
  serviceId: 256
  isDisabled: false
- name: WOWOWライブ
  type: BS
  channel: BS05_0
  serviceId: 192
  isDisabled: false
- name: WOWOWシネマ
  type: BS
  channel: BS05_1
  serviceId: 193
  isDisabled: false
- name: BS11
  type: BS
  channel: BS09_0
  serviceId: 211
- name: スター・チャンネル1
  type: BS
  channel: BS09_1
  serviceId: 200
  isDisabled: false
- name: TwellV
  type: BS
  channel: BS09_2
  serviceId: 222
- name: FOXスポーツ＆エンターテイメント
  type: BS
  channel: BS11_0
  serviceId: 238
  isDisabled: false
- name: BSスカパー!
  type: BS
  channel: BS11_1
  serviceId: 241
  isDisabled: false
- name: 放送大学BS1
  type: BS
  channel: BS11_2
  serviceId: 231
- name: 放送大学BS2
  type: BS
  channel: BS11_2
  serviceId: 232
- name: 放送大学BS3
  type: BS
  channel: BS11_2
  serviceId: 233
- name: BS日テレ
  type: BS
  channel: BS13_0
  serviceId: 141
- name: BS日テレ (sub)
  type: BS
  channel: BS13_0
  serviceId: 142
- name: BSフジ
  type: BS
  channel: BS13_1
  serviceId: 181
- name: BSアニマックス
  type: BS
  channel: BS13_2
  serviceId: 236
  isDisabled: false
- name: NHK BS1
  type: BS
  channel: BS15_0
  serviceId: 101
- name: NHK BS1 (sub)
  type: BS
  channel: BS15_0
  serviceId: 102
- name: スター・チャンネル2
  type: BS
  channel: BS15_1
  serviceId: 201
  isDisabled: false
- name: スター・チャンネル3
  type: BS
  channel: BS15_1
  serviceId: 202
  isDisabled: false
- name: グリーンチャンネル
  type: BS
  channel: BS19_0
  serviceId: 234
  isDisabled: false
- name: J SPORTS 1
  type: BS
  channel: BS19_1
  serviceId: 242
  isDisabled: false
- name: J SPORTS 2
  type: BS
  channel: BS19_2
  serviceId: 243
  isDisabled: false
- name: イマジカBS・映画
  type: BS
  channel: BS21_0
  serviceId: 252
  isDisabled: false
- name: J SPORTS 3
  type: BS
  channel: BS21_1
  serviceId: 244
  isDisabled: false
- name: J SPORTS 4
  type: BS
  channel: BS21_2
  serviceId: 245
  isDisabled: false
- name: BS釣りビジョン
  type: BS
  channel: BS23_0
  serviceId: 251
  isDisabled: false
- name: 日本映画専門チャンネル
  type: BS
  channel: BS23_1
  serviceId: 255
  isDisabled: false
- name: D-Life
  type: BS
  channel: BS23_2
  serviceId: 258
  isDisabled: false
- name: CS2
  type: CS
  channel: CS2
- name: CS4
  type: CS
  channel: CS4
- name: CS6
  type: CS
  channel: CS6
- name: CS8
  type: CS
  channel: CS8
- name: CS10
  type: CS
  channel: CS10
- name: CS12
  type: CS
  channel: CS12
- name: CS14
  type: CS
  channel: CS14
- name: CS16
  type: CS
  channel: CS16
- name: CS18
  type: CS
  channel: CS18
- name: CS20
  type: CS
  channel: CS20
- name: CS22
  type: CS
  channel: CS22
- name: CS24
  type: CS
  channel: CS24
