- name: ＮＨＫＥテレ
  type: GR
  channel: '13'
  isDisabled: false
- name: 読売テレビ
  type: GR
  channel: '14'
  isDisabled: false
- name: ＡＢＣテレビ
  type: GR
  channel: '15'
  isDisabled: false
- name: ＭＢＳ毎日放送
  type: GR
  channel: '16'
  isDisabled: false
- name: 関西テレビ
  type: GR
  channel: '17'
  isDisabled: false
- name: テレビ大阪
  type: GR
  channel: '18'
  isDisabled: false
- name: ＮＨＫ総合
  type: GR
  channel: '24'
  isDisabled: false
- name: ＢＳ朝日１
  type: BS
  channel: BS01_0
  serviceId: 151
  isDisabled: false
- name: ＢＳ朝日２
  type: BS
  channel: BS01_0
  serviceId: 152
  isDisabled: false
- name: ＢＳ朝日３
  type: BS
  channel: BS01_0
  serviceId: 153
  isDisabled: false
- name: ＢＳ－ＴＢＳ
  type: BS
  channel: BS01_1
  serviceId: 161
  isDisabled: false
- name: ＢＳ－ＴＢＳ
  type: BS
  channel: BS01_1
  serviceId: 162
  isDisabled: false
- name: ＢＳ－ＴＢＳ
  type: BS
  channel: BS01_1
  serviceId: 163
  isDisabled: false
- name: ＢＳテレ東
  type: BS
  channel: BS01_2
  serviceId: 171
  isDisabled: false
- name: ＢＳテレ東２
  type: BS
  channel: BS01_2
  serviceId: 172
  isDisabled: false
- name: ＢＳテレ東３
  type: BS
  channel: BS01_2
  serviceId: 173
  isDisabled: false
- name: ＷＯＷＯＷプライム
  type: BS
  channel: BS03_0
  serviceId: 191
  isDisabled: false
- name: ＮＨＫＢＳプレミアム
  type: BS
  channel: BS03_1
  serviceId: 103
  isDisabled: false
- name: ＮＨＫＢＳプレミアム
  type: BS
  channel: BS03_1
  serviceId: 104
  isDisabled: false
- name: ＷＯＷＯＷライブ
  type: BS
  channel: BS05_0
  serviceId: 192
  isDisabled: false
- name: ＷＯＷＯＷシネマ
  type: BS
  channel: BS05_1
  serviceId: 193
  isDisabled: false
- name: ＢＳ１１イレブン
  type: BS
  channel: BS09_0
  serviceId: 211
  isDisabled: false
- name: スターチャンネル１
  type: BS
  channel: BS09_1
  serviceId: 200
  isDisabled: false
- name: ＢＳ１２トゥエルビ
  type: BS
  channel: BS09_2
  serviceId: 222
  isDisabled: false
- name: ＢＳスカパー！
  type: BS
  channel: BS11_0
  serviceId: 241
  isDisabled: false
- name: 放送大学ｅｘ
  type: BS
  channel: BS11_1
  serviceId: 231
  isDisabled: false
- name: 放送大学ｏｎ
  type: BS
  channel: BS11_1
  serviceId: 232
  isDisabled: false
- name: ＢＳ釣りビジョン
  type: BS
  channel: BS11_2
  serviceId: 251
  isDisabled: false
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 141
  isDisabled: false
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 142
  isDisabled: false
- name: ＢＳ日テレ
  type: BS
  channel: BS13_0
  serviceId: 143
  isDisabled: false
- name: ＢＳフジ・１８１
  type: BS
  channel: BS13_1
  serviceId: 181
  isDisabled: false
- name: ＢＳフジ・１８２
  type: BS
  channel: BS13_1
  serviceId: 182
  isDisabled: false
- name: ＢＳフジ・１８３
  type: BS
  channel: BS13_1
  serviceId: 183
  isDisabled: false
- name: ＢＳアニマックス
  type: BS
  channel: BS13_2
  serviceId: 236
  isDisabled: false
- name: ＮＨＫＢＳ１
  type: BS
  channel: BS15_0
  serviceId: 101
  isDisabled: false
- name: ＮＨＫＢＳ１
  type: BS
  channel: BS15_0
  serviceId: 102
  isDisabled: false
- name: スターチャンネル２
  type: BS
  channel: BS15_1
  serviceId: 201
  isDisabled: false
- name: スターチャンネル３
  type: BS
  channel: BS15_1
  serviceId: 202
  isDisabled: false
- name: Ｊ　ＳＰＯＲＴＳ　４
  type: BS
  channel: BS19_0
  serviceId: 245
  isDisabled: false
- name: Ｊ　ＳＰＯＲＴＳ　１
  type: BS
  channel: BS19_1
  serviceId: 242
  isDisabled: false
- name: Ｊ　ＳＰＯＲＴＳ　２
  type: BS
  channel: BS19_2
  serviceId: 243
  isDisabled: false
- name: Ｊ　ＳＰＯＲＴＳ　３
  type: BS
  channel: BS19_3
  serviceId: 244
  isDisabled: false
- name: ＷＯＷＯＷプラス
  type: BS
  channel: BS21_0
  serviceId: 252
  isDisabled: false
- name: 日本映画専門ｃｈ
  type: BS
  channel: BS21_1
  serviceId: 255
  isDisabled: false
- name: グリーンチャンネル
  type: BS
  channel: BS21_2
  serviceId: 234
  isDisabled: false
- name: TBSチャンネル1
  type: CS
  channel: CS2
  serviceId: 296
- name: テレ朝チャンネル1
  type: CS
  channel: CS2
  serviceId: 298
- name: テレ朝チャンネル2
  type: CS
  channel: CS2
  serviceId: 299
- name: ディズニージュニア
  type: CS
  channel: CS2
  serviceId: 339
- name: スカイA
  type: CS
  channel: CS4
  serviceId: 250
- name: 時代劇専門ch
  type: CS
  channel: CS4
  serviceId: 292
- name: エンタメ～テレ
  type: CS
  channel: CS4
  serviceId: 301
- name: MTV
  type: CS
  channel: CS4
  serviceId: 323
- name: ホームドラマch
  type: CS
  channel: CS6
  serviceId: 294
- name: ミュージック・エア
  type: CS
  channel: CS6
  serviceId: 324
- name: 歌謡ポップスch
  type: CS
  channel: CS6
  serviceId: 329
- name: カートゥーン
  type: CS
  channel: CS6
  serviceId: 331
- name: ディスカバリーチャンネル
  type: CS
  channel: CS6
  serviceId: 340
- name: アニマルプラネット
  type: CS
  channel: CS6
  serviceId: 341
- name: CNNj
  type: CS
  channel: CS6
  serviceId: 354
- name: 囲碁・将棋チャンネル
  type: CS
  channel: CS6
  serviceId: 363
- name: 東映チャンネル
  type: CS
  channel: CS8
  serviceId: 218
- name: 日テレNEWS24
  type: CS
  channel: CS8
  serviceId: 349
- name: 衛星劇場
  type: CS
  channel: CS10
  serviceId: 219
- name: スポーツライブ+
  type: CS
  channel: CS10
  serviceId: 800
- name: スカチャン1
  type: CS
  channel: CS10
  serviceId: 801
- name: GAORA
  type: CS
  channel: CS12
  serviceId: 254
- name: エムオン！
  type: CS
  channel: CS12
  serviceId: 325
- name: キッズステーション
  type: CS
  channel: CS12
  serviceId: 330
- name: ナショナルジオグラフィック
  type: CS
  channel: CS12
  serviceId: 343
- name: ザ・シネマ
  type: CS
  channel: CS14
  serviceId: 227
- name: ファミリー劇場
  type: CS
  channel: CS14
  serviceId: 293
- name: スーパー！ドラマTV
  type: CS
  channel: CS14
  serviceId: 310
- name: ヒストリーチャンネル
  type: CS
  channel: CS14
  serviceId: 342
- name: SKY STAGE
  type: CS
  channel: CS16
  serviceId: 290
- name: AXN海外ドラマ
  type: CS
  channel: CS16
  serviceId: 311
- name: AXNミステリー
  type: CS
  channel: CS16
  serviceId: 316
- name: スペシャプラス
  type: CS
  channel: CS16
  serviceId: 321
- name: AT-X
  type: CS
  channel: CS16
  serviceId: 333
- name: BBCワールドニュース
  type: CS
  channel: CS16
  serviceId: 353
- name: ムービープラス
  type: CS
  channel: CS18
  serviceId: 240
- name: ゴルフネットワーク
  type: CS
  channel: CS18
  serviceId: 262
- name: チャンネル銀河
  type: CS
  channel: CS18
  serviceId: 305
- name: 女性ch／LaLa
  type: CS
  channel: CS18
  serviceId: 314
- name: フジテレビONE
  type: CS
  channel: CS20
  serviceId: 307
- name: フジテレビTWO
  type: CS
  channel: CS20
  serviceId: 308
- name: フジテレビNEXT
  type: CS
  channel: CS20
  serviceId: 309
- name: スペースシャワーTV
  type: CS
  channel: CS20
  serviceId: 322
- name: TBSチャンネル2
  type: CS
  channel: CS22
  serviceId: 297
- name: FOX
  type: CS
  channel: CS22
  serviceId: 312
- name: TBS NEWS
  type: CS
  channel: CS22
  serviceId: 351
- name: 映画ch・NECO
  type: CS
  channel: CS24
  serviceId: 223
- name: 日テレG+
  type: CS
  channel: CS24
  serviceId: 257
- name: MONDO TV
  type: CS
  channel: CS24
  serviceId: 295
- name: 日テレプラス
  type: CS
  channel: CS24
  serviceId: 300
