apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress
  namespace: wordpress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wordpress-exec
  namespace: wordpress
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress
  namespace: wordpress
subjects:
  - kind: ServiceAccount
    name: wordpress
    namespace: wordpress
roleRef:
  kind: Role
  name: wordpress-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: wordpress-cronjob
  namespace: wordpress
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: wordpress
          containers:
            - name: kubectl
              image: ghcr.io/akashisn/kubectl@sha256:934b15b6d873838cedc17ef804f4da83d6b19236f60f0fec1800693185cc074b
              imagePullPolicy: IfNotPresent
              args:
                [
                  "exec",
                  "-n",
                  "wordpress",
                  "wordpress-0",
                  "-c",
                  "wordpress",
                  "--",
                  "/bin/sh",
                  "-c",
                  'su www-data --shel=/bin/sh --command="/usr/local/bin/php -f /var/www/html/wp-cron.php"',
                ]
          restartPolicy: Never
