apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iscsi-ssd-storage
  claimRef:
    namespace: wordpress
    name: app-wordpress-0
  iscsi:
    targetPortal: 10.254.0.2:3260
    iqn: iqn.2005-10.org.freenas.ctl:wordpress
    lun: 0
    fsType: xfs
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-mariadb-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iscsi-ssd-storage
  claimRef:
    namespace: wordpress
    name: data-wordpress-mariadb-0
  iscsi:
    targetPortal: 10.254.0.2:3260
    iqn: iqn.2005-10.org.freenas.ctl:wordpress-mariadb
    lun: 0
    fsType: xfs
    readOnly: false
