version: "3.8"

services:
  #
  # TV
  #

  mirakurun:
    image: ghcr.io/akashisn/mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    devices:
      - /dev/bus:/dev/bus
      - /dev/dvb:/dev/dvb
    volumes:
      - ./mirakurun/config/:/app-config/
      - ./mirakurun/data/:/app-data/
    environment:
      TZ: Asia/Tokyo
      LOG_LEVEL: "3"
    expose:
      - "40772"
    networks:
      internal:
    restart: always

  mariadb_epgstation:
    image: mariadb:10.8
    volumes:
      - mariadb_epgstation:/var/lib/mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_USER: epgstation
      MYSQL_PASSWORD: ${MYSQL_EPGSTATION_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_EPGSTATION_ROOT_PASSWORD}
      MYSQL_DATABASE: epgstation
    expose:
      - "3306"
    networks:
      internal:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1
    restart: always

  epgstation:
    image: ghcr.io/akashisn/epgstation
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./epgstation/config:/app/config
      - ./epgstation/thumbnail:/app/thumbnail
      - /media/recorded:/app/recorded
    devices:
      - /dev/dri:/dev/dri
    environment:
      TZ: "Asia/Tokyo"
      HOME: /app
      DOMAIN: ${DOMAIN}
      MYSQL_PASSWORD: ${MYSQL_EPGSTATION_PASSWORD}
    expose:
      - "8888"
    networks:
      internal:
    depends_on:
      - mirakurun
      - mariadb_epgstation
    command: >
      /bin/sh -c
        "envsubst '$$MYSQL_PASSWORD $$DOMAIN' < /app/config/config.yml.template > /app/config/config.yml
        npm start"
    restart: always

  #
  # DNS
  #

  dnsmasq:
    image: ghcr.io/akashisn/dnsmasq@sha256:e1125fba16d30716c9d0baf4dc3b01b67130e48541fc7caa11ed31818d5783b7
    volumes:
      - type: bind
        source: ./dns/conf/dnsmasq.conf
        target: /etc/dnsmasq.d/dnsmasq.conf
        read_only: true
    environment:
      TZ: "Asia/Tokyo"
    expose:
      - "10053/udp"
    networks:
      internal:
        ipv4_address: "172.20.0.10"
      external:
    restart: always

  dnsdist:
    image: ghcr.io/akashisn/dnsdist@sha256:3ae0e1f42c2eccfaaa236e494f9891a63bd0767193c4e1f38943dead35f587fc
    volumes:
      - type: bind
        source: ./dns/conf/dnsdist.conf
        target: /etc/dnsdist.conf
        read_only: true
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true
    environment:
      TZ: "Asia/Tokyo"
    expose:
      - "53/udp"
      - "443/tcp"
      - "853/tcp"
    ports:
      - "53:53/udp"
      - "853:853/tcp"
    networks:
      internal:
      external:
        ipv6_address: ${DOCKER_IPV6_SUBNET}::50
    restart: always

  #
  # Nginx
  #

  nginx:
    image: nginx:mainline
    volumes:
      - ./nginx/conf.d:/run/nginx:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      TZ: "Asia/Tokyo"
    expose:
      - "443"
    ports:
      - "443:443"
    networks:
      internal:
      external:
        ipv6_address: ${DOCKER_IPV6_SUBNET}::33
    depends_on:
      - epgstation
    command: >
      /bin/sh -c
        "cp /run/nginx/nginx.conf /etc/nginx/nginx.conf
        cp /run/nginx/real_ip.conf /etc/nginx/conf.d/real_ip.conf
        cp /run/nginx/tv.conf /etc/nginx/conf.d/tv.conf
        nginx -g 'daemon off;'"
    restart: always

volumes:
  mariadb_epgstation:
    driver: local
  log_volume:
    driver: local

networks:
  internal:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
  external:
    external: true
