version: "3.8"

services:
  #
  # TV
  #

  mirakurun:
    image: ghcr.io/akashisn/dvb-docker/mirakurun
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    devices:
      - /dev/bus:/dev/bus
      - /dev/dvb:/dev/dvb
    volumes:
      - ./mirakurun/config/:/app-config/
      - ./mirakurun/data/:/app-data/
    environment:
      TZ: Asia/Tokyo
      LOG_LEVEL: "3"
    expose:
      - "40772"
    networks:
      internal:
    restart: always

  mariadb_epgstation:
    image: mariadb:10.8
    volumes:
      - mariadb_epgstation:/var/lib/mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_USER: epgstation
      MYSQL_PASSWORD: ${MYSQL_EPGSTATION_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_EPGSTATION_ROOT_PASSWORD}
      MYSQL_DATABASE: epgstation
    expose:
      - "3306"
    networks:
      internal:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1
    restart: always

  epgstation:
    image: ghcr.io/akashisn/dvb-docker/epgstation:5.0-qsv
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./epgstation/config:/app/config
      - ./epgstation/thumbnail:/app/thumbnail
      - /media/recorded:/app/recorded
      - log_volume:/var/promtail
    devices:
      - /dev/dri:/dev/dri
    environment:
      TZ: "Asia/Tokyo"
      HOME: /app
      DOMAIN: ${DOMAIN}
      MYSQL_PASSWORD: ${MYSQL_EPGSTATION_PASSWORD}
    expose:
      - "8888"
    networks:
      internal:
    depends_on:
      - mirakurun
      - mariadb_epgstation
    command: >
      /bin/sh -c
        "mkdir -p /var/promtail/epgstation
        rm -rf /app/logs
        ln -snf /var/promtail/epgstation /app/logs
        envsubst '$$MYSQL_PASSWORD $$DOMAIN' < /app/config/config.yml.template > /app/config/config.yml
        npm start"
    restart: always

  #
  # Nginx
  #

  nginx:
    image: ghcr.io/akashisn/nginx
    volumes:
      - ./nginx/conf.d:/run/nginx:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - log_volume:/var/promtail
    environment:
      TZ: "Asia/Tokyo"
      DOMAIN: ${DOMAIN}
    expose:
      - "443"
    ports:
      - "443:443"
    networks:
      internal:
      external:
        ipv6_address: ${DOCKER_IPV6_SUBNET}::33
    depends_on:
      - epgstation
    command: >
      /bin/sh -c
        "mkdir -p /var/promtail/nginx
        rm -rf /etc/nginx/conf.d/*
        envsubst '$$DOMAIN' < /run/nginx/nginx.conf.template > /etc/nginx/nginx.conf
        envsubst '$$DOMAIN' < /run/nginx/tv.conf.template > /etc/nginx/conf.d/tv.conf
        /usr/bin/supervisord -c /etc/supervisord.conf"
    restart: always

  #
  # DNS
  #

  dnsmasq:
    image: ghcr.io/akashisn/dnsmasq
    expose:
      - "53"
    networks:
      external:
    ports:
      - "${LOCAL_IP}:53:53/udp"
    restart: always

  #
  # ddclient
  #

  ddclient:
    image: ghcr.io/akashisn/ddclient
    volumes:
      - ./ddclient:/run/ddclient:ro
    environment:
      TZ: "Asia/Tokyo"
      ZONE: ${DOMAIN}
      CLOUDFLARE_TOKEN: ${CLOUDFLARE_TOKEN}
      TARGET_RECORDS: "vpn.${DOMAIN}"
    networks:
      external:
    command: >
      /bin/sh -c
        "envsubst '$$ZONE $$CLOUDFLARE_TOKEN $$TARGET_RECORDS' < /run/ddclient/ddclient.conf.template > /etc/ddclient/ddclient.conf
        /usr/bin/crond"
    restart: always

volumes:
  mariadb_epgstation:
    driver: local
  log_volume:
    driver: local

networks:
  internal:
    internal: true
  external:
    external: true
