---
# file: roles/helm/tasks/main.yml

# helm
- name: Add stable Helm charts repository
  kubernetes.core.helm_repository:
    name: stable
    repo_url: https://charts.helm.sh/stable
  become: false

- import_tasks: cilium.yml
- import_tasks: metallb.yml
- import_tasks: nginx-ingress.yml
- import_tasks: cert-manager.yml
- import_tasks: metrics-server.yml
- import_tasks: prometheus.yml

- name: Restart coredns
  ansible.builtin.command:
    cmd: "kubectl -n kube-system rollout restart deployment coredns"
  become: false
