---
# file: roles/helm/tasks/prometheus.yml
- name: Add prometheus Helm charts repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
  become: false

- name: Check if prometheus-stack Helm chart is installed
  shell: helm list --all-namespaces --deployed --short | grep prometheus-stack
  register: prometheus_stack_helm_chart_result
  changed_when: prometheus_stack_helm_chart_result.rc != 0
  ignore_errors: yes
  become: false

- name: Deploy prometheus-stack chart using set values on target
  kubernetes.core.helm:
    release_name: prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    update_repo_cache: true
    wait: true
    atomic: true
    release_values:
      grafana:
        adminPassword: "{{ grafana_admin_password }}"
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
          hosts:
            - "{{ grafana_host }}"
          tls:
            - secretName: letsencrypt-cert
              hosts:
              - "{{ grafana_host }}"
  when: prometheus_stack_helm_chart_result.rc != 0
  become: false
