apiVersion: v1
kind: Secret
metadata:
  name: vso-secrets
  namespace: palworld
  annotations:
    replicator.v1.mittwald.de/replicate-from: vault-secrets-operator/vso-secrets
type: Opaque
data: {}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: palworld-secrets
  namespace: palworld
spec:
  appName: palworld
  hcpAuthRef: vault-secrets-operator/hcp-auth
  destination:
    create: true
    name: palworld-secrets
