apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argo-cd
spec:
  syncWindows:
    - kind: allow
      schedule: '0 2 * * *'
      timeZone: "Asia/Tokyo"
      duration: 1h
      manualSync: true
      applications:
        - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: server-config
  namespace: argo-cd
spec:
  generators:
    - list:
        elements:
          # - name: dns
          # - name: minecraft
          - name: nextcloud
          # - name: wordpress
          - name: immich
          # - name: tv
  template:
    metadata:
      name: "{{name}}"
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{name}}"
      project: default
      source:
        path: "kubernetes/k8s/{{name}}"
        repoURL: https://github.com/AkashiSN/Server-Config.git
        targetRevision: main
      syncPolicy:
        automated: {}
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - kind: Secret
          jsonPointers:
            - /data
