apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: wordpress
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: wordpress
          image: ghcr.io/akashisn/wordpress@sha256:8638f732c543c62fdea18760bd42e67f3baf7f16e0c7e5d972a23f0605dcb450
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never