apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-photos-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-hdd-storage
  nfs:
    server: 10.254.0.2
    path: /mnt/hdd/nfs/immich-photos
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-postgres-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iscsi-ssd-storage
  claimRef:
    namespace: immich
    name: data-immich-postgres-0
  nfs:
    server: 10.254.0.2
    path: /mnt/ssd/nfs/immich-postgres
  mountOptions:
    - nfsvers=4.2
