apiVersion: batch/v1
kind: Job
metadata:
  name: image-pull-job
  namespace: immich
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v1.139.4
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
        - name: immich-machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v1.140.1
          command: ["/bin/sh"]
          args: ["-c", "exit 0"]
      restartPolicy: Never
