apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iscsi-ssd-storage
  claimRef:
    namespace: grafana
    name: data-grafana-0
  iscsi:
    targetPortal: 172.16.255.2:3260
    iqn: iqn.2005-10.org.freenas.ctl:grafana
    lun: 0
    fsType: xfs
    readOnly: false