apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: server-config
  namespace: argo-cd
spec:
  generators:
    - list:
        elements:
          - name: dns
          - name: minecraft
          - name: nextcloud
          - name: wordpress
  template:
    metadata:
      name: "{{name}}"
    spec:
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{name}}"
      project: default
      source:
        path: "k8s/manifests/{{name}}"
        repoURL: https://github.com/AkashiSN/Server-Config.git
        targetRevision: main
      syncPolicy:
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - kind: Secret
          jsonPointers:
            - /data
