apiVersion: v1
kind: Namespace
metadata:
  name: dns
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: minecraft
---
apiVersion: v1
kind: Namespace
metadata:
  name: nextcloud
---
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
