---
# file: roles/delete/tasks/nextcloud.yml
- name: Delete the nextcloud cronjob config
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('file', 'manifests/nextcloud/cronjob.yml') | from_yaml_all }}"
  become: false

- name: Delete the nextcloud config
  kubernetes.core.k8s:
    state: absent
    template: manifests/nextcloud/nextcloud.yml.j2
    wait: true
  become: false

- name: Delete the nextcloud redis config
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('file', 'manifests/nextcloud/redis.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Delete the nextcloud mariadb config
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('file', 'manifests/nextcloud/mariadb.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Delete the nextcloud nginx-conf config
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('file', 'manifests/nextcloud/nginx-conf.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Delete the nextcloud persistent-volumes config
  kubernetes.core.k8s:
    state: absent
    template: manifests/nextcloud/persistent-volume.yml.j2
  become: false
