---
# file: roles/delete/tasks/wordpress.yml
- name: Delete the wordpress/cronjob manifest
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('file', 'manifests/wordpress/cronjob.yml') | from_yaml_all }}"
  become: false

- name: Delete the wordpress/wordpress manifest
  kubernetes.core.k8s:
    state: absent
    template: manifests/wordpress/wordpress.yml
    wait: true
  become: false

- name: Delete the wordpress/redis manifest
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('file', 'manifests/wordpress/redis.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Delete the wordpress/mariadb manifest
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('file', 'manifests/wordpress/mariadb.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Delete the wordpress/nginx-conf manifest
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('file', 'manifests/wordpress/nginx-conf.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Delete the wordpress/persistent-volumes manifest
  kubernetes.core.k8s:
    state: absent
    template: manifests/wordpress/persistent-volume.yml
  become: false
