appenders:
  system:
    type: dateFile
    backups: 31
    filename: "%OperatorSystem%"
    pattern: "-yyyy-MM-dd"
  access:
    type: dateFile
    maxLogSize: 1048576
    backups: 31
    filename: "%OperatorAccess%"
    pattern: "-yyyy-MM-dd"
  stream:
    type: dateFile
    maxLogSize: 1048576
    backups: 31
    filename: "%OperatorStream%"
    pattern: "-yyyy-MM-dd"
  encode:
    type: dateFile
    maxLogSize: 1048576
    backups: 31
    filename: "%OperatorEncode%"
    pattern: "-yyyy-MM-dd"
  console:
    type: console
  stdout:
    type: stdout
categories:
  default:
    appenders:
      - console
      - stdout
    level: info
  system:
    appenders:
      - system
      - stdout
    level: info
  access:
    appenders:
      - access
      - stdout
    level: info
  stream:
    appenders:
      - stream
      - stdout
    level: info