---
# file: setup-cluster.yml
- name: Setup common for kubeadm
  hosts: virtualmachines
  gather_facts: false
  any_errors_fatal: true
  pre_tasks:
    - name: Gather facts for target hosts
      ansible.builtin.setup:
      when: inventory_hostname != "k3s"
  roles:
    - role: variable
      when: inventory_hostname != "k3s"
    - role: common
      vars:
        os: "xUbuntu_24.04"
        k8s_major_version: "1.32"
      when: inventory_hostname != "k3s"

- name: Setup cluster by kubeadm
  hosts: virtualmachines
  gather_facts: false
  any_errors_fatal: true
  pre_tasks:
    - name: Gather facts for target hosts
      ansible.builtin.setup:
      when: inventory_hostname != "k3s"
  roles:
    - role: variable
      when: inventory_hostname != "k3s"
    - role: cluster
      vars:
        target_env: "staging" # staging or production
        pod_subnet: "10.132.0.0/16"
        service_subnet: "11.132.0.0/16"
      when: inventory_hostname != "k3s"
