---
# file: roles/manifests/tasks/dns.yml
- name: Create the 'dns' namespace
  kubernetes.core.k8s:
    state: present
    api_version: v1
    name: dns
    kind: Namespace
  become: false

- name: Check if dns cronjob is deployed
  shell: kubectl get -n dns cronjob dns-cronjob
  register: dns_cronjob_result
  changed_when: false
  ignore_errors: true
  become: false

- name: Delete dns cronjob
  shell: kubectl delete -n dns cronjob dns-cronjob
  when: dns_cronjob_result.rc == 0
  become: false

- name: Apply the dns config
  kubernetes.core.k8s:
    state: present
    template: manifests/dns/dns.yml.j2
    wait: false # because of certificate acme challenge
  become: false

- name: Wait for all pods to be ready
  command: kubectl get pods -n dns -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}'
  register: result
  until: result.stdout.find("False") == -1
  retries: 60
  delay: 10
  become: false

- name: Apply the dns cronjob config
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/dns/cronjob.yml') | from_yaml_all }}"
  become: false
