---
# file: roles/manifests/tasks/dns.yml
- name: Create the 'dns' namespace
  kubernetes.core.k8s:
    state: present
    api_version: v1
    name: dns
    kind: Namespace

- name: Apply the dns config
  kubernetes.core.k8s:
    state: present
    template: manifests/dns/dns.yml.j2

- name: Apply the dns cronjob config
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/dns/cronjob.yml') | from_yaml_all }}"
