---
# file: roles/manifests/tasks/dns.yml
- name: Create the 'dns' namespace
  kubernetes.core.k8s:
    state: present
    api_version: v1
    name: dns
    kind: Namespace
  become: false

- name: Check if the dns/cronjob is deployed
  ansible.builtin.command:
    cmd: kubectl get -n dns cronjob dns-cronjob
  register: dns_cronjob_result
  changed_when: false
  ignore_errors: true
  become: false

- name: Delete the dns/cronjob
  ansible.builtin.command:
    cmd: kubectl delete -n dns cronjob dns-cronjob
  register: result
  when: dns_cronjob_result.rc == 0
  changed_when: result is not skipped
  become: false

- name: Set loadBalancerIPs
  ansible.builtin.set_fact: # noqa jinja[spacing]
    dns_load_balancer_ips: >-
      {%- if default_interface_v6.stdout != "" -%}
      {{ dns_lb_v4_addr }},{{ ipv6_prefix.stdout }}:{{ dns_lb_v6_host_addr }}
      {%- else -%}
      {{ dns_lb_v4_addr }}
      {%- endif -%}
  become: false

- name: Apply the dns/dns manifest
  kubernetes.core.k8s:
    state: present
    template: manifests/dns/dns.yml
    wait: false # because of certificate acme challenge
  become: false

- name: Wait for all pods to be ready
  ansible.builtin.command:
    cmd: kubectl get pods -n dns -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}'
  register: result
  until: result.stdout.find("False") == -1
  retries: 60
  delay: 10
  changed_when: false
  become: false

- name: Apply the dns/cronjob manifest
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/dns/cronjob.yml') | from_yaml_all }}"
  become: false
