---
# file: roles/manifests/tasks/main.yml
- name: Wait until all pods are ready or completed
  shell: |
    kubectl get pods -A -o jsonpath='{range .items[*]}{.metadata.name}:{.status.phase}{"\n"}{end}'
  register: pod_status
  until: >
    pod_status.stdout.splitlines() |
    map('regex_search', ':(Running|Succeeded)$') |
    select('defined') |
    list |
    length == pod_status.stdout.splitlines() | length
  retries: 60
  delay: 10
  changed_when: false
  become: false

- name: Apply the storage class config
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/storage-class.yml') | from_yaml_all }}"
  become: false

- import_tasks: dns.yml
- import_tasks: minecraft.yml
- import_tasks: nextcloud.yml
- import_tasks: wordpress.yml
