---
# file: roles/manifests/tasks/nextcloud.yml
- name: Create the 'nextcloud' namespace
  kubernetes.core.k8s:
    state: present
    api_version: v1
    name: nextcloud
    kind: Namespace
  become: false

- name: Create the nextcloud/nextcloud-secrets
  kubernetes.core.k8s:
    state: present
    api_version: v1
    namespace: nextcloud
    name: nextcloud-secrets
    kind: Secret
    definition:
      type: Opaque
      data:
        nextcloud_admin_user: "{{ nextcloud_admin_user | b64encode }}"
        nextcloud_admin_password: "{{ nextcloud_admin_password | b64encode }}"
        nextcloud_mariadb_root_password: "{{ nextcloud_mariadb_root_password | b64encode }}"
        nextcloud_mariadb_user_password: "{{ nextcloud_mariadb_user_password | b64encode }}"
        nextcloud_smtp_user: "{{ nextcloud_smtp_user | b64encode }}"
        nextcloud_smtp_password: "{{ nextcloud_smtp_password | b64encode }}"
  become: false

- name: Apply the nextcloud/persistent-volumes manifest
  kubernetes.core.k8s:
    state: present
    template: manifests/nextcloud/persistent-volume.yml.j2
  become: false

- name: Check if the nextcloud/cronjob is deployed
  ansible.builtin.command:
    cmd: kubectl get -n nextcloud cronjob nextcloud-cronjob
  register: nextcloud_cronjob_result
  changed_when: false
  ignore_errors: true
  become: false

- name: Delete the nextcloud/cronjob
  ansible.builtin.command:
    cmd: kubectl delete -n nextcloud cronjob nextcloud-cronjob
  register: result
  when: nextcloud_cronjob_result.rc == 0
  changed_when: result is not skipped
  become: false

- name: Apply the nextcloud/redis manifest
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/nextcloud/redis.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Apply the nextcloud/mariadb manifest
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/nextcloud/mariadb.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Apply the nextcloud/nginx-conf manifest
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/nextcloud/nginx-conf.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Apply the nextcloud/nextcloud-conf manifest
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/nextcloud/nextcloud-conf.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Apply the nextcloud/nextcloud manifest
  kubernetes.core.k8s:
    state: present
    template: manifests/nextcloud/nextcloud.yml.j2
    wait: true
  become: false

- name: Wait for all pods to be ready
  ansible.builtin.command:
    cmd: kubectl get pods -n nextcloud -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}'
  register: result
  until: result.stdout.find("False") == -1
  retries: 60
  delay: 10
  changed_when: false
  become: false

- name: Apply the nextcloud/cronjob manifest
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/nextcloud/cronjob.yml') | from_yaml_all }}"
  become: false
