---
# file: roles/manifests/tasks/wordpress.yml
- name: Create the 'wordpress' namespace
  kubernetes.core.k8s:
    state: present
    api_version: v1
    name: wordpress
    kind: Namespace
  become: false

- name: Create wordpress-secrets
  kubernetes.core.k8s:
    state: present
    api_version: v1
    namespace: wordpress
    name: wordpress-secrets
    kind: Secret
    definition:
      type: Opaque
      data:
        wordpress_mariadb_root_password: "{{ wordpress_mariadb_root_password | b64encode }}"
        wordpress_mariadb_user_password: "{{ wordpress_mariadb_user_password | b64encode }}"
        wordpress_admin_user: "{{ wordpress_admin_user | b64encode }}"
        wordpress_admin_password: "{{ wordpress_admin_password | b64encode }}"
        wordpress_admin_email: "{{ wordpress_admin_email | b64encode }}"
  become: false

- name: Apply the wordpress persistent-volumes config
  kubernetes.core.k8s:
    state: present
    template: manifests/wordpress/persistent-volume.yml.j2
  become: false

- name: Check if wordpress cronjob is deployed
  ansible.builtin.command:
    cmd: kubectl get -n wordpress cronjob wordpress-cronjob
  register: wordpress_cronjob_result
  changed_when: false
  ignore_errors: true
  become: false

- name: Delete wordpress cronjob
  ansible.builtin.command:
    cmd: kubectl delete -n wordpress cronjob wordpress-cronjob
  register: result
  when: wordpress_cronjob_result.rc == 0
  changed_when: result is not skipped
  become: false

- name: Apply the wordpress redis config
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/wordpress/redis.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Apply the wordpress mariadb config
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/wordpress/mariadb.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Apply the wordpress nginx-conf config
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/wordpress/nginx-conf.yml') | from_yaml_all }}"
    wait: true
  become: false

- name: Apply the wordpress config
  kubernetes.core.k8s:
    state: present
    template: manifests/wordpress/wordpress.yml.j2
    wait: true
  become: false

- name: Wait for all pods to be ready
  ansible.builtin.command:
    cmd: kubectl get pods -n wordpress -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}'
  register: result
  until: result.stdout.find("False") == -1
  retries: 60
  delay: 10
  changed_when: false
  become: false

- name: Apply the wordpress cronjob config
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'manifests/wordpress/cronjob.yml') | from_yaml_all }}"
  become: false
