---
# file: roles/kubeadm/tasks/main.yml
- name: Copy kubeadm-config.yml.j2 configuration template
  ansible.builtin.template:
    src: kubeadm-config.yml.j2
    dest: /root/kubeadm-config.yml
    mode: 0644
  delegate_to: master-node
  become: true

- name: Check if Kubernetes is already initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_initialized
  changed_when: false
  delegate_to: master-node
  become: true

- name: Run kubeadm init
  ansible.builtin.command:
    cmd: kubeadm init --skip-phases=addon/kube-proxy --config=/root/kubeadm-config.yml
  when: not kubernetes_initialized.stat.exists
  register: kubeadm_init_result
  delegate_to: master-node
  become: true

- name: Get kubeadm join command
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  register: join_command
  when: kubeadm_init_result is changed
  delegate_to: master-node
  become: true

- name: Join the cluster
  ansible.builtin.command:
    cmd: "{{ join_command.stdout }} --ignore-preflight-errors=all"
  register: join_result
  when: kubeadm_init_result is changed
  delegate_to: worker-node
  become: true

- name: Create .kube directory in the user's home
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
  delegate_to: master-node
  become: false

- name: Copy admin.conf to user's tmp directory
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/tmp/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
    remote_src: true
  delegate_to: master-node
  become: true

- name: Copy tmp to user's .kube directory
  ansible.builtin.copy:
    src: /tmp/config
    dest: "{{ ansible_env.HOME }}/.kube/config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
    remote_src: true
  delegate_to: master-node
  become: false

- name: Remove tmp files
  ansible.builtin.file:
    path: /tmp/config
    state: absent
  become: true

- name: Approve pending certificates
  block:
    - name: Get pending CSR names
      shell: kubectl get csr | grep Pending | awk '{print $1}'
      register: pending_csr_result

    - name: Approve each pending CSR
      shell: kubectl certificate approve {{ item }}
      with_items: "{{ pending_csr_result.stdout_lines }}"
  delegate_to: master-node
  become: false
