version: "3.8"

services:
  #
  # loki
  #
  loki:
    image: grafana/loki
    command: >
      -print-config-stderr
    ports:
      - "3100:3100"
    restart: always

  #
  # grafana
  #
  mariadb_grafana:
    image: mariadb:10.5
    volumes:
      - mariadb_grafana:/var/lib/mysql
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_USER: ${MYSQL_GRAFANA_USER}
      MYSQL_PASSWORD: ${MYSQL_GRAFANA_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_GRAFANA_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_GRAFANA_DATABASE}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --performance-schema=false --expire_logs_days=1
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
    environment:
      TZ: "Asia/Tokyo"
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_HOST: mariadb_grafana:3306
      GF_DATABASE_NAME: ${MYSQL_GRAFANA_DATABASE}
      GF_DATABASE_USER: ${MYSQL_GRAFANA_USER}
      GF_DATABASE_PASSWORD: ${MYSQL_GRAFANA_PASSWORD}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - mariadb_grafana
    ports:
      - "3000:3000"
    restart: always

volumes:
  mariadb_grafana:
    driver: local
  grafana:
    driver: local
