---
# file: roles/cluster/tasks/cilium.yml
- name: Add cilium Helm charts repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
  become: false

- name: Check if cilium Helm chart is installed
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      helm list --all-namespaces --deployed --short | grep cilium
    executable: /bin/bash
  register: cilium_helm_chart_result
  changed_when: cilium_helm_chart_result.rc != 0
  ignore_errors: true
  become: false

- name: Deploy cilium chart using set values on target
  kubernetes.core.helm:
    release_name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    update_repo_cache: true
    wait: true
    atomic: true
    release_values:
      bpf:
        masquerade: true
      enableIPv6Masquerade: false
      ipam:
        mode: cluster-pool
        operator:
          clusterPoolIPv4PodCIDRList: "10.244.0.0/16"
          clusterPoolIPv6PodCIDRList: "{{ ipv6_prefix.stdout }}:{{ ipv6_pod_cider }}"
          clusterPoolIPv4MaskSize: 24
          clusterPoolIPv6MaskSize: 112
      ipv4:
        enabled: true
      ipv6:
        enabled: true
      k8sServiceHost: "{{ node_ip.stdout }}"
      k8sServicePort: 6443
      kubeProxyReplacement: strict
      dashboards:
        enabled: true
        namespace: monitoring
        label: grafana_dashboard
        labelValue: "1"
      prometheus:
        enabled: true
      operator:
        dashboards:
          enabled: true
          namespace: monitoring
          label: grafana_dashboard
          labelValue: "1"
        prometheus:
          enabled: true
  register: cilium_helm_chart_install
  when: cilium_helm_chart_result.rc != 0
  become: false

- name: Patch cilium-config ConfigMap
  ansible.builtin.shell: >
    kubectl -n kube-system patch configmap/cilium-config --type merge
    -p "{\"data\":{\"enable-ipv6-ndp\": \"true\", \"ipv6-service-range\": \"{{ ipv6_prefix.stdout }}:{{ ipv6_service_cider }}\"}}"
  register: result
  when: cilium_helm_chart_install is not skipped
  changed_when: result is not skipped
  become: false

- name: Restart cilium
  ansible.builtin.command:
    cmd: "kubectl -n kube-system rollout restart {{ item.target }}"
  loop:
    - target: deploy cilium-operator
    - target: daemonset cilium
  register: result
  when: cilium_helm_chart_install is not skipped
  changed_when: result is not skipped
  become: false

- name: Wait for all pods to be ready
  ansible.builtin.command:
    cmd: kubectl get pods -n kube-system -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}'
  register: result
  until: result.stdout.find("False") == -1
  retries: 60
  delay: 10
  changed_when: false
  become: false
