---
# file: roles/cluster/tasks/main.yml

- name: kubeadm init
  ansible.builtin.import_tasks:
    file: kubeadm.yml
  when: inventory_hostname != "microk8s"

# helm
- name: helm setup
  block:
    - name: helm
      ansible.builtin.import_tasks:
        file: helm.yml

    - name: cilium
      ansible.builtin.import_tasks:
        file: cilium.yml
      when: inventory_hostname != "microk8s"

    - name: metallb
      ansible.builtin.import_tasks:
        file: metallb.yml

    - name: nginx-ingress
      ansible.builtin.import_tasks:
        file: nginx-ingress.yml

    - name: cert-manager
      ansible.builtin.import_tasks:
        file: cert-manager.yml

    - name: metrics-server
      ansible.builtin.import_tasks:
        file: metrics-server.yml
      when: inventory_hostname != "microk8s"

    - name: democratic-csi
      ansible.builtin.import_tasks:
        file: democratic-csi.yml
      when: inventory_hostname != "microk8s"

    - name: monitoring
      ansible.builtin.import_tasks:
        file: monitoring.yml
      when: inventory_hostname != "microk8s"
  when: inventory_hostname in groups["master"]
  become: false

- name: Wait for all pods to be ready
  command: kubectl get pods -A -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}'
  register: result
  until: result.stdout.find("False") == -1
  retries: 60
  delay: 10
  when: inventory_hostname in groups["master"]
  become: false
