---
# file: roles/cluster/tasks/main.yml

# kubeadm init
- import_tasks: kubeadm.yml

# helm
- name: helm setup
  block:
    - import_tasks: helm.yml
    - import_tasks: cilium.yml
    - import_tasks: metallb.yml
    - import_tasks: nginx-ingress.yml
    - import_tasks: cert-manager.yml
    - import_tasks: metrics-server.yml
    - import_tasks: democratic-csi.yml
    - import_tasks: monitoring.yml
  when: inventory_hostname == "master-node"
  become: false

- name: Wait for all pods to be ready
  command: kubectl get pods -A -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}'
  register: result
  until: result.stdout.find("False") == -1
  retries: 60
  delay: 10
  when: inventory_hostname == "master-node"
  become: false
