---
# file: roles/cluster/tasks/main.yml

# kubeadm init
- import_tasks: kubeadm.yml

# helm
- name: helm setup
  block:
    - import_tasks: helm.yml
    - import_tasks: cilium.yml
    - import_tasks: metallb.yml
    - import_tasks: nginx-ingress.yml
    - import_tasks: cert-manager.yml
    - import_tasks: metrics-server.yml
    - import_tasks: democratic-csi.yml
    - import_tasks: monitoring.yml
  when: inventory_hostname == "master-node"
  become: false

- name: Wait until all pods are ready or completed
  shell: |
    kubectl get pods -A -o jsonpath='{range .items[*]}{.metadata.name}:{.status.phase}{"\n"}{end}'
  register: pod_status
  until: >
    pod_status.stdout.splitlines() |
    map('regex_search', ':(Running|Succeeded)$') |
    select('defined') |
    list |
    length == pod_status.stdout.splitlines() | length
  retries: 60
  delay: 10
  changed_when: false
  when: inventory_hostname == "master-node"
  become: false
