---
# file: roles/cluster/tasks/nginx-ingress.yml
- name: Add nginx-stable Helm charts repository
  kubernetes.core.helm_repository:
    name: nginx-stable
    repo_url: https://helm.nginx.com/stable
  become: false

- name: Check if nginx-ingress Helm chart is installed
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      helm list --all-namespaces --deployed --short | grep nginx-ingress
    executable: /bin/bash
  register: nginx_ingress_helm_chart_result
  changed_when: nginx_ingress_helm_chart_result.rc != 0
  ignore_errors: true
  become: false

- name: Concat cloudflare_ips strings
  ansible.builtin.set_fact:
    real_ip_from: "{{ cloudflare_ips | join(', ') }}, {{ local_ips | join(',') }}, {{ external_ip }}"
  become: false

- name: Deploy nginx-ingress chart using set values on target
  kubernetes.core.helm:
    release_name: nginx-ingress
    chart_ref: nginx-stable/nginx-ingress
    release_namespace: nginx-ingress
    create_namespace: true
    update_repo_cache: true
    wait: true
    atomic: true
    values: "{{ lookup('template', 'nginx-ingress-values.yml.j2') | from_yaml }}"
  register: nginx_ingress_helm_chart_install
  when: nginx_ingress_helm_chart_result.rc != 0
  become: false
