---
# file: roles/cluster/tasks/oauth2-proxy.yml
- name: Add oauth2-proxy Helm charts repository
  kubernetes.core.helm_repository:
    name: oauth2-proxy
    repo_url: https://oauth2-proxy.github.io/manifests
  become: false

- name: Deploy oauth2-proxy chart using set values on target
  kubernetes.core.helm:
    release_name: oauth2-proxy
    chart_ref: oauth2-proxy/oauth2-proxy
    release_namespace: auth
    update_repo_cache: true
    wait: false
    atomic: true
    release_values:
      extraArgs:
        provider: oidc
        provider-display-name: dex
        client-id: "oauth2-proxy"
        client-secret: "{{ oauth2_proxy_client_secret }}"
        whitelist-domain: ".{{ domain }}"
        cookie-domain: ".{{ domain }}"
        redirect-url: "https://{{ auth_fqdn }}/oauth2/callback"
        oidc-issuer-url: "https://{{ auth_fqdn }}/dex"
        cookie-secure: "true"
      ingress:
        enabled: false
  become: false
