---
# file: roles/cluster/tasks/oauth2-proxy.yml
- name: Add oauth2-proxy Helm charts repository
  kubernetes.core.helm_repository:
    name: oauth2-proxy
    repo_url: https://oauth2-proxy.github.io/manifests
  become: false

- name: Deploy oauth2-proxy chart using set values on target
  kubernetes.core.helm:
    release_name: oauth2-proxy
    chart_ref: oauth2-proxy/oauth2-proxy
    chart_version: "7.1.*"
    release_namespace: auth
    update_repo_cache: true
    wait: false
    atomic: true
    values: "{{ lookup('template', 'oauth2-proxy-values.yml.j2') | from_yaml }}"
  become: false
