---
# file: roles/cluster/tasks/prometheus.yml
- name: Add prometheus Helm charts repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
  become: false

- name: Check if prometheus-stack Helm chart is installed
  shell: helm list --all-namespaces --deployed --short | grep prometheus-stack
  register: prometheus_stack_helm_chart_result
  changed_when: prometheus_stack_helm_chart_result.rc != 0
  ignore_errors: yes
  become: false

- name: Deploy prometheus-stack chart using set values on target
  kubernetes.core.helm:
    release_name: prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    update_repo_cache: true
    wait: true
    atomic: true
    release_values:
      prometheus:
        prometheusSpec:
          additionalScrapeConfigs:
            - job_name: 'node-service-discovery'
              kubernetes_sd_configs:
                - role: node
              relabel_configs:
                - source_labels: [__meta_kubernetes_node_annotation_prometheus_io_scrape]
                  action: keep
                  regex: true
                - source_labels: [__meta_kubernetes_node_annotation_prometheus_io_scheme]
                  action: replace
                  target_label: __scheme__
                  regex: (https?)
                - source_labels: [__meta_kubernetes_node_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - source_labels: [__address__, __meta_kubernetes_node_annotation_prometheus_io_port]
                  action: replace
                  target_label: __address__
                  regex: ([^:]+)(?::\d+)?;(\d+)
                  replacement: $1:$2
            - job_name: 'svc-service-discovery'
              kubernetes_sd_configs:
                - role: service
              relabel_configs:
                - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
                  action: keep
                  regex: true
                - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
                  action: replace
                  target_label: __scheme__
                  regex: (https?)
                - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
                  action: replace
                  target_label: __address__
                  regex: ([^:]+)(?::\d+)?;(\d+)
                  replacement: $1:$2
            - job_name: 'pod-service-discovery'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  action: keep
                  regex: true
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
                  action: replace
                  target_label: __scheme__
                  regex: (https?)
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                  action: replace
                  target_label: __address__
                  regex: ([^:]+)(?::\d+)?;(\d+)
                  replacement: $1:$2
            - job_name: 'ingress-service-discovery'
              kubernetes_sd_configs:
                - role: ingress
              relabel_configs:
                - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_scrape]
                  action: keep
                  regex: true
                - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_scheme]
                  action: replace
                  target_label: __scheme__
                  regex: (https?)
                - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - source_labels: [__address__, __meta_kubernetes_ingress_annotation_prometheus_io_port]
                  action: replace
                  target_label: __address__
                  regex: ([^:]+)(?::\d+)?;(\d+)
                  replacement: $1:$2
      grafana:
        adminPassword: "{{ grafana_admin_password }}"
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
          hosts:
            - "{{ grafana_host }}"
          tls:
            - secretName: letsencrypt-cert
              hosts:
              - "{{ grafana_host }}"
  when: prometheus_stack_helm_chart_result.rc != 0
  become: false
