server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/promtail/positions.yaml

clients:
  - url: http://172.16.100.3:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/promtail/nginx/*.log
  - job_name: epgstation
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/promtail/epgstation/**/*.log
  - job_name: nextcloud
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/promtail/nextcloud/*.log