apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: iscsi-ssd-storage
  claimRef:
    namespace: minecraft
    name: data-minecraft-vanilla-0
  iscsi:
    targetPortal: "{{ truenas_addr }}:3260"
    iqn: iqn.2005-10.org.freenas.ctl:minecraft
    lun: 0
    fsType: xfs
    readOnly: false