epg:
  cache-dir: /var/lib/mirakc/epg

server:
  # Replace `localhost` with `0.0.0.0` (ipv4) or `::` (ipv6) if you like to
  # connect from other hosts.
  addrs:
    - http: '0.0.0.0:40772'

# from scan_channel.sh
channels:
  - name: 'ＮＨＫＥテレ１大阪'
    type: 'GR'
    channel: '13'
    extra-args: ''
    disabled: false

  - name: '読売テレビ１'
    type: 'GR'
    channel: '14'
    extra-args: ''
    disabled: false

  - name: 'ＡＢＣテレビ１'
    type: 'GR'
    channel: '15'
    extra-args: ''
    disabled: false

  - name: 'ＭＢＳ毎日放送'
    type: 'GR'
    channel: '16'
    extra-args: ''
    disabled: false

  - name: '関西テレビ１'
    type: 'GR'
    channel: '17'
    extra-args: ''
    disabled: false

  - name: 'テレビ大阪１'
    type: 'GR'
    channel: '18'
    extra-args: ''
    disabled: false

  - name: 'ＮＨＫ総合１・大阪'
    type: 'GR'
    channel: '24'
    extra-args: ''
    disabled: false

  - name: 'ＢＳ朝日１'
    type: 'BS'
    channel: 'BS01_0'
    extra-args: ''
    disabled: false

  - name: 'ＢＳ－ＴＢＳ'
    type: 'BS'
    channel: 'BS01_1'
    extra-args: ''
    disabled: false

  - name: 'ＢＳテレ東'
    type: 'BS'
    channel: 'BS01_2'
    extra-args: ''
    disabled: false

  - name: 'ＷＯＷＯＷプライム'
    type: 'BS'
    channel: 'BS03_0'
    extra-args: ''
    disabled: false

  - name: 'ＷＯＷＯＷライブ'
    type: 'BS'
    channel: 'BS05_0'
    extra-args: ''
    disabled: false

  - name: 'ＷＯＷＯＷシネマ'
    type: 'BS'
    channel: 'BS05_1'
    extra-args: ''
    disabled: false

  - name: 'スターチャンネル１'
    type: 'BS'
    channel: 'BS09_1'
    extra-args: ''
    disabled: false

  - name: '放送大学テレビ'
    type: 'BS'
    channel: 'BS11_0'
    extra-args: ''
    disabled: false

  - name: 'ＢＳ日テレ'
    type: 'BS'
    channel: 'BS13_0'
    extra-args: ''
    disabled: false

  - name: 'ＢＳアニマックス'
    type: 'BS'
    channel: 'BS13_2'
    extra-args: ''
    disabled: false

  - name: 'スターチャンネル２'
    type: 'BS'
    channel: 'BS15_0'
    extra-args: ''
    disabled: false

  - name: 'Ｊ　ＳＰＯＲＴＳ　１'
    type: 'BS'
    channel: 'BS19_1'
    extra-args: ''
    disabled: false

tuners:
  - name: DDMaxM4-0
    types:
      - GR
      - BS
    command: dvbv5-zap -a 0 -c /etc/mirakc/isdb.conf -r -P {{{channel}}} -o -

  - name: DDMaxM4-1
    types:
      - GR
      - BS
    command: dvbv5-zap -a 1 -c /etc/mirakc/isdb.conf -r -P {{{channel}}} -o -

  - name: DDMaxM4-2
    types:
      - GR
      - BS
    command: dvbv5-zap -a 2 -c /etc/mirakc/isdb.conf -r -P {{{channel}}} -o -

  - name: DDMaxM4-3
    types:
      - GR
      - BS
    command: dvbv5-zap -a 3 -c /etc/mirakc/isdb.conf -r -P {{{channel}}} -o -

filters:
  decode-filter:
    command: arib-b25-stream
