epg:
  cache-dir: /var/lib/mirakc/epg

server:
  # Replace `localhost` with `0.0.0.0` (ipv4) or `::` (ipv6) if you like to
  # connect from other hosts.
  addrs:
    - http: '0.0.0.0:40772'

channels:
  - name: NHKEテレ
    type: GR
    channel: '13'
  - name: 読売テレビ
    type: GR
    channel: '14'
  - name: ABCテレビ
    type: GR
    channel: '15'
  - name: MBS毎日放送
    type: GR
    channel: '16'
  - name: 関西テレビ
    type: GR
    channel: '17'
  - name: テレビ大阪
    type: GR
    channel: '18'
  - name: NHK総合
    type: GR
    channel: '24'
  - name: BS朝日 151
    type: BS
    channel: BS01_0
    services: [151]
  - name: BS朝日 152
    type: BS
    channel: BS01_0
    services: [152]
  - name: BS朝日 153
    type: BS
    channel: BS01_0
    services: [153]
  - name: BS-TBS 161
    type: BS
    channel: BS01_1
    services: [161]
  - name: BS-TBS 162
    type: BS
    channel: BS01_1
    services: [162]
  - name: BS-TBS 163
    type: BS
    channel: BS01_1
    services: [163]
  - name: BSテレ東 171
    type: BS
    channel: BS01_2
    services: [171]
  - name: BSテレ東 172
    type: BS
    channel: BS01_2
    services: [172]
  - name: BSテレ東 173
    type: BS
    channel: BS01_2
    services: [173]
  - name: WOWOWプライム
    type: BS
    channel: BS03_0
    services: [191]
  - name: NHKBSプレミアム 103
    type: BS
    channel: BS03_1
    services: [103]
  - name: NHKBSプレミアム 104
    type: BS
    channel: BS03_1
    services: [104]
  - name: WOWOWライブ
    type: BS
    channel: BS05_0
    services: [192]
  - name: WOWOWシネマ
    type: BS
    channel: BS05_1
    services: [193]
  - name: BS11イレブン
    type: BS
    channel: BS09_0
    services: [211]
  - name: スターチャンネル1
    type: BS
    channel: BS09_1
    services: [200]
  - name: BS12トゥエルビ
    type: BS
    channel: BS09_2
    services: [222]
  - name: BSスカパー!
    type: BS
    channel: BS11_0
    services: [241]
  - name: 放送大学ex
    type: BS
    channel: BS11_1
    services: [231]
  - name: 放送大学on
    type: BS
    channel: BS11_1
    services: [232]
  - name: BS釣りビジョン
    type: BS
    channel: BS11_2
    services: [251]
  - name: BS日テレ 141
    type: BS
    channel: BS13_0
    services: [141]
  - name: BS日テレ 142
    type: BS
    channel: BS13_0
    services: [142]
  - name: BS日テレ 143
    type: BS
    channel: BS13_0
    services: [143]
  - name: BSフジ 181
    type: BS
    channel: BS13_1
    services: [181]
  - name: BSフジ 182
    type: BS
    channel: BS13_1
    services: [182]
  - name: BSフジ 183
    type: BS
    channel: BS13_1
    services: [183]
  - name: BSアニマックス
    type: BS
    channel: BS13_2
    services: [236]
  - name: NHKBS 101
    type: BS
    channel: BS15_0
    services: [101]
  - name: NHKBS 102
    type: BS
    channel: BS15_0
    services: [102]
  - name: スターチャンネル2
    type: BS
    channel: BS15_1
    services: [201]
  - name: スターチャンネル3
    type: BS
    channel: BS15_1
    services: [202]
  - name: J SPORTS 4
    type: BS
    channel: BS19_0
    services: [245]
  - name: J SPORTS 1
    type: BS
    channel: BS19_1
    services: [242]
  - name: J SPORTS 2
    type: BS
    channel: BS19_2
    services: [243]
  - name: J SPORTS 3
    type: BS
    channel: BS19_3
    services: [244]
  - name: WOWOWプラス
    type: BS
    channel: BS21_0
    services: [252]
  - name: 日本映画専門ch
    type: BS
    channel: BS21_1
    services: [255]
  - name: グリーンチャンネル
    type: BS
    channel: BS21_2
    services: [234]

tuners:
  - name: DDMaxM4-0
    types:
      - GR
    command: dvbv5-zap -a 0 -c /etc/mirakc/isdb.conf -r -P {{{channel}}} -o -

  - name: DDMaxM4-1
    types:
      - GR
    command: dvbv5-zap -a 1 -c /etc/mirakc/isdb.conf -r -P {{{channel}}} -o -

  - name: DDMaxM4-2
    types:
      - BS
    command: dvbv5-zap --lnbf=110BS -a 2 -c /etc/mirakc/isdb.conf -r -P {{{channel}}} -o -

  - name: DDMaxM4-3
    types:
      - BS
    command: dvbv5-zap --lnbf=110BS -a 3 -c /etc/mirakc/isdb.conf -r -P {{{channel}}} -o -

filters:
  decode-filter:
    command: arib-b25-stream
