---
# file: roles/common/tasks/main.yml
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  become: true

- name: Install a list of common packages
  ansible.builtin.apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - open-iscsi
    - python3-pip
    - jq
    - sysstat
    state: present
    update_cache: true
  become: true

- name: install kubernetes pre-requisites
  ansible.builtin.pip:
    name:
      - pyyaml
      - kubernetes
  become: false

- import_tasks: dns.yml
- import_tasks: timezone.yml
- import_tasks: swap.yml
- import_tasks: logrotate.yml
- import_tasks: kernel.yml
- import_tasks: watchdog.yml

- name: for kubeadm
  block:
    - import_tasks: iptables.yml
    - import_tasks: helm.yml
    - import_tasks: crio.yml
    - import_tasks: kubeadm.yml
  when: inventory_hostname != "microk8s"

- name: for microk8s
  ansible.builtin.import_tasks:
    file: microk8s.yml
  when: inventory_hostname == "microk8s"

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  become: true
