---
# file: roles/common/tasks/swap.yml
- name: Turn off swap
  ansible.builtin.command:
    cmd: swapoff -a
  changed_when: false
  become: true

- name: Comment out swap entries in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^(?!#)(.+swap.+)'
    line: '#\1'
    backrefs: true
  become: true
