name: auto-merge

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'dependabot/') ||
        startsWith(github.head_ref, 'actions/') ||
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Approve PR
        run: gh pr review "$PR_URL" --approve

      - name: Enable auto-merge for PRs
        run: gh pr merge --merge --auto "$PR_URL"
