name: auto-merge

on:
  pull_request:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'dependabot/') ||
        startsWith(github.head_ref, 'actions/')
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.AUTO_MERGE_BOT_APP_ID }}
          private_key: ${{ secrets.AUTO_MERGE_BOT_PRIVATE_KEY }}

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ steps.generate_token.outputs.token }}

      - name: Approve & enable auto-merge for Dependabot/Actions PR
        run: |
          gh pr review --approve "$PR_URL"
          gh pr edit "$PR_URL" -t "(auto merged) $PR_TITLE"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
