name: ddclient

on:
  push:
    paths:
      - 'compose/ddclient/**'
      - '!compose/ddclient/**.md'
      - '.github/workflows/ddclient.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: akashisn
          password: ${{ github.token }}

      - name: Build and push - ddclient
        uses: docker/build-push-action@v2
        with:
          context: ./compose/ddclient
          file: ./compose/ddclient/Dockerfile
          tags: |
            ghcr.io/akashisn/ddclient
          platforms: linux/amd64
          push: true
