name: dnsmasq

on:
  workflow_dispatch:
  push:
    paths:
      - 'docker/dnsmasq/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: akashisn
          password: ${{ github.token }}

      - name: Build and push - dnsmasq
        uses: docker/build-push-action@v5
        with:
          context: ./docker/dnsmasq
          file: ./docker/dnsmasq/Dockerfile
          tags: |
            ghcr.io/akashisn/dnsmasq
          platforms: linux/amd64
          push: true
