name: hackmd

on:
  push:
    paths:
      - 'docker/hackmd/**'
      - '.github/workflows/hackmd.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: akashisn
          password: ${{ github.token }}

      - name: Build and push - hackmd
        uses: docker/build-push-action@v4
        with:
          context: ./docker/hackmd
          file: ./docker/hackmd/Dockerfile
          tags: |
            ghcr.io/akashisn/hackmd
          platforms: linux/amd64
          push: true
