name: kubectl-update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # (At 00:00 on day-of-month 1)

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.UPDATE_BOT_APP_ID }}
          private-key: ${{ secrets.UPDATE_BOT_PRIVATE_KEY }}

      - name: Check for Kubernetes updates
        id: check-update
        run: |
          CURRENT_KUBE_VERSION=$(sed -n -r -e "s/.*KUBE_VERSION=\"(.*)\"/\1/p" ./docker/kubectl/Dockerfile)
          LATEST_KUBE_VERSION=$(curl -LS https://dl.k8s.io/release/stable.txt)
          echo "current=$CURRENT_KUBE_VERSION" >> $GITHUB_OUTPUT
          echo "latest=$LATEST_KUBE_VERSION" >> $GITHUB_OUTPUT

      - name: Apply update & Create commit
        if: steps.check-update.outputs.current != steps.check-update.outputs.latest
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git switch -c actions/kubectl-${{ steps.check-update.outputs.latest }}

          sed -i -r -e "s/(KUBE_VERSION=)\".*\"/\1\"${{ steps.check-update.outputs.latest }}\"/g" ./docker/kubectl/Dockerfile

          git add ./docker/kubectl/Dockerfile
          git commit -m "Bump kubectl from ${{ steps.check-update.outputs.current }} to ${{ steps.check-update.outputs.latest }} in /docker/kubectl"
          git push --set-upstream origin actions/kubectl-${{ steps.check-update.outputs.latest }}

      - name: Create pull request
        if: steps.check-update.outputs.current != steps.check-update.outputs.latest
        run: |
          gh pr create -B main -H actions/kubectl-${{ steps.check-update.outputs.latest }} \
            --title 'Bump kubectl from ${{ steps.check-update.outputs.current }} to ${{ steps.check-update.outputs.latest }} in /docker/kubectl' \
            --body 'Bumps kubectl from `${{ steps.check-update.outputs.current }}` to `${{ steps.check-update.outputs.latest }}`.'
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
