name: mirakurun

on:
  push:
    paths:
      - 'docker/mirakurun/**'
      - '.github/workflows/mirakurun.yml'
  workflow_run:
    workflows: ["v4l-utils", "libarib25"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: akashisn
          password: ${{ github.token }}

      - name: Build and push - mirakurun
        uses: docker/build-push-action@v4
        with:
          context: ./docker/mirakurun
          file: ./docker/mirakurun/Dockerfile
          tags: |
            ghcr.io/akashisn/mirakurun
          platforms: linux/amd64
          push: true
