name: mirakc

on:
  push:
    paths:
      - 'docker/mirakc/**'
      - '.github/workflows/mirakc.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: akashisn
          password: ${{ github.token }}

      - name: Build and push - mirakc
        uses: docker/build-push-action@v5
        with:
          context: ./docker/mirakc
          file: ./docker/mirakc/Dockerfile
          tags: |
            ghcr.io/akashisn/mirakc
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
