name: nextcloud

on:
  push:
    paths:
      - 'nextcloud/**'
      - '!nextcloud/**.md'
      - '.github/workflows/nextcloud.yml'
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ github.workflow }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.workflow }}-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: akashisn
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push - nextcloud
        uses: docker/build-push-action@v2
        with:
          context: ./nextcloud
          file: ./nextcloud/Dockerfile
          tags: |
            akashisn/nextcloud
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
