name: nextcloud

on:
  push:
    paths:
      - 'k8s/nextcloud/Dockerfile'
      - '.github/workflows/nextcloud.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: akashisn
          password: ${{ github.token }}

      - name: Build and push - nextcloud
        uses: docker/build-push-action@v2
        with:
          context: ./k8s/nextcloud
          file: ./k8s/nextcloud/Dockerfile
          tags: |
            ghcr.io/akashisn/nextcloud
          platforms: linux/amd64
          push: true
