name: nextcloud

on:
  push:
    paths:
      - 'docker/nextcloud/**'
      - '.github/workflows/nextcloud.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: akashisn
          password: ${{ github.token }}

      - name: Build and push - nextcloud
        uses: docker/build-push-action@v5
        with:
          context: ./docker/nextcloud
          file: ./docker/nextcloud/Dockerfile
          tags: |
            ghcr.io/akashisn/nextcloud
          platforms: linux/amd64
          push: true
