name: v4l-utils

on:
  push:
    paths:
      - 'docker/v4l-utils/**'
      - '.github/workflows/v4l-utils.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: akashisn
          password: ${{ github.token }}

      - name: Build and push - v4l-utils
        uses: docker/build-push-action@v3
        with:
          context: ./docker/v4l-utils
          file: ./docker/v4l-utils/Dockerfile
          tags: |
            ghcr.io/akashisn/v4l-utils
          platforms: linux/amd64
          push: true
